"""Conteúdo autoral para estudar sem console; integrado a gerar_docs.py.

As linhas usam campos separados por |. Não use esse caractere dentro de um campo.
Tópicos: id, funcionamento, decisão, limite, cenário, resposta comentada.
Fichas: nome, recursos, escolhas, fluxo, capacidade/condição, limite, caso comentado.
"""

def linhas(texto, campos):
    resultado = {}
    for linha in texto.strip().splitlines():
        partes = [p.strip() for p in linha.split('|')]
        assert len(partes) == campos, f'Campos inválidos: {linha}'
        chave, *valores = partes
        assert chave not in resultado, f'Chave duplicada: {chave}'
        resultado[chave] = valores
    return resultado

TOPICOS = linhas("""
1.1 | A conta identifica o proprietário e a cobrança; serviços entregam recursos por APIs. Você escolhe o nível de gerenciamento: servidor, plataforma ou aplicação pronta. Console, CLI e SDK são formas de pedir operações a essas APIs. | Compare o que sua equipe precisa administrar: EC2 entrega a máquina virtual; RDS administra parte do banco; SaaS entrega a aplicação para uso. Híbrido combina ambiente próprio e nuvem. | Usar a AWS não transfere automaticamente a responsabilidade pelos dados, acessos e aplicações. Nem todo serviço gerenciado é gratuito ou dispensa configuração. | Uma empresa quer instalar um sistema que exige administrar o Linux. Que modelo atende e quem atualiza o SO? | IaaS com EC2; o cliente atualiza o SO convidado. Em RDS, esse controle é reduzido porque a AWS administra o sistema do banco.
1.2 | Capacidade é disponibilizada conforme a demanda, em vez de ser comprada para um pico futuro. A escala da AWS permite compartilhar infraestrutura entre clientes com isolamento. | Identifique o problema: capital antecipado, preço por volume, previsão de capacidade, demora de implantação, manutenção de datacenter ou alcance geográfico. | A nuvem oferece meios de economizar; recursos ociosos, tráfego e configurações inadequadas ainda geram despesas. Agilidade não é sinônimo de menor preço. | Uma loja mantém servidores para a Black Friday que ficam ociosos o resto do ano. Qual vantagem resolve isso? | Deixar de adivinhar capacidade, combinado com elasticidade: aumentar no pico e reduzir depois. Comprar uma máquina maior permanentemente continua deixando capacidade ociosa.
1.3 | Escala vertical aumenta uma máquina; horizontal adiciona máquinas. Filas desacoplam produtores e consumidores. Redundância reduz impacto de falhas; backups permitem voltar a uma cópia anterior. | Separe três requisitos: crescer, continuar disponível e recuperar depois de um desastre. Para recuperação, RTO trata do tempo fora do ar; RPO trata da perda tolerável de dados. | Multi-AZ não recupera automaticamente uma exclusão lógica replicada. Backup não mantém, por si só, o sistema disponível durante a falha. Escalar não elimina gargalos de banco. | Uma empresa aceita ficar duas horas fora do ar e perder até dez minutos de dados. Quais objetivos deve registrar? | RTO de duas horas e RPO de dez minutos. São metas diferentes: restaurar rapidamente uma cópia antiga pode cumprir o RTO e descumprir o RPO.
1.4 | A revisão avalia uma carga nos seis pilares; a Well-Architected Tool registra respostas, riscos e melhorias. Ela ajuda a revisar decisões, sem implantar a arquitetura por você. | Operação e aprendizado: Excelência Operacional. Identidade e proteção: Segurança. Falhas e recuperação: Confiabilidade. Recursos adequados: Performance. Gasto: Custos. Impacto ambiental: Sustentabilidade. | Uma prática pode ajudar vários pilares. Escolha o pilar pelo objetivo expresso no enunciado; Graviton não significa automaticamente que a pergunta é sobre sustentabilidade. | Uma equipe automatiza procedimentos e revê incidentes para melhorar sua operação. Qual pilar é o principal? | Excelência Operacional. Se o objetivo destacado fosse recuperar a carga após falhas, o foco seria Confiabilidade.
1.5 | O CAF organiza capacidades da empresa nas perspectivas Business, People, Governance, Platform, Security e Operations. Envision define resultados; Align identifica lacunas; Launch testa iniciativas; Scale amplia o que funciona. | Use quem é responsável e qual mudança é necessária: treinamento e cultura pertencem a People; decisões sobre investimento e risco, a Governance; infraestrutura e padrões técnicos, a Platform. | CAF não é um serviço que migra servidores nem substitui uma revisão técnica do Well-Architected. Adoção inclui organização, habilidades e processos. | A infraestrutura já funciona, mas faltam habilidades e adaptação de funções na equipe. Qual perspectiva precisa de atenção? | People. Escolher Platform só porque o projeto usa AWS ignora que o impedimento é organizacional.
1.6 | Avalie cada aplicação e suas dependências antes de escolher um dos 7 Rs. A estratégia orienta ferramentas, esforço e testes; aplicações da mesma empresa podem ter destinos distintos. | Sem mudar aplicação: Rehost. Pequeno ajuste: Replatform. Redesenho: Refactor. Troca por SaaS: Repurchase. Desligar: Retire. Manter: Retain. Mover a plataforma: Relocate. | Rehost não moderniza automaticamente a aplicação. Refactor demanda mudanças e não é sempre a opção mais rápida. Uma ferramenta de migração não decide a estratégia de negócio. | Um banco instalado em servidor próprio vai para RDS, mantendo a aplicação com poucos ajustes. Qual estratégia? | Replatform: há mudança da plataforma operacional. Levar o mesmo servidor e banco para EC2 sem ajustes seria Rehost.
1.7 | TCO inclui equipamento, energia, espaço, pessoal, licenças e operação. Rightsizing ajusta capacidade ao uso observado; automação reduz tarefas repetitivas. | Compare custo total e requisitos, não apenas preço de uma instância. BYOL reaproveita licenças elegíveis; licença incluída simplifica aquisição conforme o serviço e o produto. | License Manager não concede licença comercial. Desconto por compromisso pode gerar desperdício se a carga desaparecer. Estimativas dependem das premissas informadas. | Uma instância está superdimensionada e a equipe quer economizar. Comprar compromisso primeiro resolve? | Primeiro avalie rightsizing e demanda. Comprometer um valor acima da necessidade pode prender a empresa a gasto desnecessário; compromisso vem depois de entender o consumo.
2.1 | Na EC2, a AWS mantém infraestrutura e hipervisor, e o cliente mantém SO e aplicação. No RDS, a AWS também administra SO e tarefas do banco. Em Lambda, o cliente mantém código, bibliotecas e permissões. | Pergunte qual camada o serviço gerencia e qual decisão o cliente continua tomando. Dados, acesso e uso adequado permanecem responsabilidades do cliente. | Gerenciado não significa segurança automática da aplicação. Em RDS, o cliente ainda decide acesso, parâmetros aplicáveis, retenção e proteção dos dados. | Quem corrige uma biblioteca vulnerável empacotada na função Lambda? | O cliente. O gerenciamento da infraestrutura e do runtime gerenciado pela AWS não corrige automaticamente as dependências incluídas no pacote do cliente.
2.2 | Root representa a identidade principal da conta, com permissões que exigem proteção especial. MFA adiciona verificação; identidades federadas e roles servem ao trabalho cotidiano. | Use root apenas para tarefas que a documentação exige. Diferencie conta standalone de conta membro sob gerenciamento centralizado de root no Organizations. | Uma política AdministratorAccess não transforma um usuário IAM em root. Evite decorar uma lista antiga de tarefas exclusivas; consulte a lista oficial, porque ela muda. | Uma pessoa administradora precisa alterar uma configuração comum. Deve entrar com root só porque é administradora? | Não. Use uma identidade com a permissão necessária; confirme root apenas quando a tarefa estiver na lista oficial de exigências.
2.3 | Autenticação confirma a identidade; autorização avalia a ação sobre o recurso. Policies definem permissões; roles fornecem sessões temporárias. Grupos agrupam usuários IAM, não roles. | Funcionários em várias contas: IAM Identity Center. Aplicação na EC2: role. Clientes de um aplicativo: Cognito. API requer credenciais apropriadas, normalmente temporárias. | Um Allow pode ser limitado por boundary ou SCP, e um Deny explícito prevalece. MFA não concede autorização. Criar usuário não fornece acesso automaticamente. | Uma aplicação na EC2 precisa ler um bucket e não deve guardar chaves de longa duração. O que usar? | IAM role associada à instância. A aplicação obtém credenciais temporárias; ainda é preciso permitir as operações no bucket e, se aplicável, na chave KMS.
2.4 | Organizations agrupa contas em OUs; SCPs limitam permissões máximas das contas membro. Control Tower estabelece uma landing zone com controles e contas de governança. | Separe organização de contas, controles comuns e compartilhamento de recursos. RAM compartilha tipos de recurso suportados; Service Catalog oferece produtos aprovados. | SCP não concede acesso e não é firewall. Faturamento consolidado não mistura dados das contas. Control Tower não elimina a administração e conformidade do cliente. | Uma empresa quer impedir determinada operação em contas de desenvolvimento. Basta anexar uma SCP com Allow? | Não. SCP define o teto; as identidades ainda precisam de permissões IAM. Uma restrição em nível organizacional pode impedir a operação mesmo com AdministratorAccess na conta membro.
2.5 | TLS protege o caminho da comunicação; criptografia em repouso protege os dados armazenados. KMS administra chaves e autoriza operações criptográficas; ACM administra certificados. | Necessidade de chave para EBS/S3: KMS. Certificado TLS: ACM. HSM dedicado com controle de usuários e chaves: CloudHSM. Segredo de aplicação: Secrets Manager. | Dado criptografado não fica automaticamente inacessível a um usuário autorizado. Criptografia não substitui IAM, backup ou requisitos de localização dos dados. | Um arquivo está em S3 com SSE-KMS. Dar apenas permissão de leitura no S3 é suficiente? | Pode não ser: o leitor também precisa de autorização adequada para usar a chave KMS. Criptografia e acesso ao objeto são camadas diferentes.
2.6 | Artifact disponibiliza documentos de conformidade da AWS. Config registra configuração e avalia regras. Evidências do ambiente do cliente ajudam uma auditoria, mas exigem interpretação. | Relatório da infraestrutura AWS: Artifact. Histórico e avaliação de recurso: Config. Regras do setor e localização dos dados: avalie regiões, serviços e suas obrigações. | A certificação da AWS não certifica automaticamente a aplicação do cliente. Uma regra conforme no Config não prova que todos os requisitos legais foram atendidos. | Um auditor pede o relatório de conformidade da AWS, não o histórico do banco da empresa. Qual recurso? | AWS Artifact. CloudTrail registra atividades da conta; Config registra configurações. Eles não substituem o documento solicitado.
2.7 | CloudWatch trabalha com métricas, logs e alarmes; CloudTrail registra atividades e chamadas; Config acompanha configuração e conformidade de recursos suportados. | CPU elevada: CloudWatch. Quem alterou a instância: CloudTrail. Qual era a configuração e se atendia uma regra: Config. Evento da infraestrutura AWS: Health. | Alarmes e registros precisam de configuração e retenção adequadas. CloudTrail não inclui todo evento de dados por padrão; métricas de memória da EC2 exigem coleta adicional. | Uma regra de segurança mudou e você quer saber quem mudou e como o recurso estava antes. Um único serviço resolve as duas perguntas? | CloudTrail ajuda a identificar a ação e a identidade; Config mostra o histórico de configuração. CloudWatch complementa com o efeito operacional.
2.8 | Security groups controlam tráfego em interfaces e mantêm estado; NACLs controlam tráfego de subnets e são sem estado. WAF avalia requisições web; Shield atua contra DDoS. | Porta de acesso de uma EC2: SG. Regra de subnet com negação: NACL. SQL injection em HTTP: WAF. Proteção distribuída contra negação de serviço: Shield. | Uma rota não concede permissão IAM; SG não examina SQL injection. Regras de retorno precisam ser consideradas em NACLs. Associar WAF exige recurso suportado. | Uma API recebe requisições com padrões de SQL injection. Abrir ou fechar a porta 443 no SG trata o padrão malicioso? | Não. WAF avalia a requisição HTTP; SG só decide o tráfego de rede permitido. Fechar 443 bloquearia também os usuários legítimos.
2.9 | GuardDuty detecta ameaças; Inspector avalia vulnerabilidades em recursos suportados; Macie descobre dados sensíveis em S3; Security Hub agrega e prioriza achados e postura. | Identifique a pergunta: comportamento suspeito, software vulnerável, conteúdo sensível ou visão centralizada. Detective ajuda a investigar contexto. | Um achado não corrige a aplicação sozinho. Resposta automática requer integração e permissões. Macie não é varredura genérica de todos os bancos e discos. | Há preocupação com credenciais expostas em objetos S3 e com biblioteca vulnerável em EC2. Qual serviço para cada parte? | Macie para descoberta de dados sensíveis no S3; Inspector para vulnerabilidades em EC2 elegível. GuardDuty responde a outra pergunta: sinais de ameaça.
2.10 | Documentação, Security Blog e Knowledge Center explicam práticas e problemas; Marketplace oferece soluções de terceiros; Trust and Safety recebe denúncias de abuso. | Diferencie proteção da sua carga, suporte técnico e denúncia de atividade abusiva em recursos AWS. As ferramentas cumprem papéis complementares. | Comprar um produto de segurança não transfere todas as obrigações ao fornecedor. Testes de segurança devem observar a política AWS e a titularidade dos recursos. | Uma empresa recebe tráfego abusivo de um recurso AWS de outra conta. Deve tentar alterar esse recurso com IAM? | Não. Pode denunciar ao Trust and Safety com evidências. Suas permissões IAM administram recursos autorizados, não os de terceiros.
3.1 | Console fornece interface visual; CLI executa comandos; SDK integra APIs ao código. CloudFormation descreve recursos e suas dependências em templates e stacks. | Operação pontual: console pode bastar. Automação repetida: CLI/SDK. Ambiente reproduzível: IaC. Híbrido mantém parte no ambiente próprio com conectividade apropriada. | Mudar de interface não amplia permissões. Templates não tornam recursos gratuitos. Scripts imperativos precisam lidar com erros e repetição; IaC registra o estado desejado. | A equipe recria o mesmo ambiente de teste toda semana. Qual abordagem reduz divergências? | IaC com CloudFormation, em vez de repetir cliques manualmente. A stack usa permissões e gera custos dos recursos criados.
3.2 | Uma região reúne AZs; cada AZ é um domínio de falha com um ou mais datacenters. Edge locations aproximam entrega e serviços de usuários. | Multi-AZ para disponibilidade regional; múltiplas regiões para requisitos como recuperação regional, residência de dados e latência. CloudFront usa a borda para entrega de conteúdo. | Escolher outra região não copia automaticamente recursos e dados. Edge não equivale a uma AZ em que você instala qualquer EC2. Multi-AZ não cobre todos os desastres regionais. | A aplicação deve continuar após falha de uma AZ. Basta criar duas EC2 na mesma subnet? | Não: uma subnet pertence a uma AZ. Distribua componentes entre AZs e considere balanceamento, estado e banco, não apenas número de instâncias.
3.3 | AMI define a base do sistema; tipo define CPU e memória; subnet define localização; EBS guarda dados; SG controla tráfego; role autoriza chamadas AWS da aplicação. | Escolha a família pelo gargalo: CPU, memória, armazenamento ou aceleração. Controle de SO aponta para EC2; menor gestão de infraestrutura pode apontar para alternativas gerenciadas. | Instância ligada e ociosa continua cobrada. Parar uma EC2 com EBS não elimina cobranças de volumes, snapshots e outros recursos. Encerrar não equivale a parar. | Você terminou um estudo e parou a EC2. A fatura necessariamente fica zerada? | Não. A computação para na condição aplicável, mas os volumes EBS e recursos mantidos ainda podem custar. Compromissos de compra também permanecem.
3.4 | Load balancer recebe tráfego e escolhe destinos saudáveis. Auto Scaling ajusta quantidade de instâncias e substitui instâncias não saudáveis conforme configuração. | ALB para HTTP e regras por host/caminho; NLB para transporte e requisitos como IP estático. Auto Scaling mantém capacidade dentro dos mínimos e máximos definidos. | Balanceador não cria sozinho novas instâncias. Auto Scaling não compartilha automaticamente sessões gravadas no disco local. Saúde e capacidade do banco também importam. | Na Black Friday o tráfego triplica. Um load balancer sem capacidade adicional garante atendimento? | Não. Ele distribui a capacidade existente. Auto Scaling adiciona instâncias quando suas políticas e limites permitem; a aplicação precisa suportar o crescimento.
3.5 | ECR armazena imagens; ECS/EKS organizam execução; Fargate fornece capacidade sem administrar hosts. Uma função Lambda executa código em resposta a uma invocação. | Kubernetes necessário: EKS. Orquestração AWS: ECS. Containers sem hosts: Fargate. Função convencional por evento: Lambda. Separe orquestrador, imagem e capacidade. | Serverless significa servidores administrados pelo provedor. A função convencional tem limite de execução por invocação; não generalize esse limite a todo recurso novo do Lambda. | Você guardou uma imagem no ECR. Sua API já está rodando? | Não: ECR é registro. É preciso executar a imagem em capacidade adequada, como ECS com Fargate, configurar rede, acesso e exposição da API.
3.6 | Beanstalk implanta uma aplicação e gerencia recursos do ambiente; Lightsail simplifica infraestrutura em pacotes; Batch organiza trabalhos em filas; Outposts leva infraestrutura AWS ao local do cliente. | Enviar aplicação web com menor esforço operacional: Beanstalk. Projeto simples com pacote: Lightsail. Lotes e jobs: Batch. Exigência local com serviços AWS compatíveis: Outposts. | Beanstalk não dispensa manutenção do código; Batch não é endpoint web interativo. Outposts ainda exige infraestrutura física e conectividade do cliente. | Uma equipe quer executar milhares de simulações independentes, que terminam após o trabalho. Qual serviço combina com isso? | AWS Batch: filas, definições de jobs e ambientes de computação. Um balanceador distribui tráfego, mas não agenda essa carga de lotes.
3.7 | Relacionais organizam tabelas e relações; NoSQL atende modelos como chave-valor/documentos; cache guarda dados de acesso rápido; warehouse prioriza análises agregadas. | RDS/Aurora para relacional; DynamoDB para chave-valor/documentos; ElastiCache para cache; DocumentDB para documentos compatíveis; Neptune para grafos; Redshift para analytics. | Gerenciado não elimina desenho de esquema, índices e consultas. Compatibilidade não significa identidade completa de APIs. Cache não deve ser confundido automaticamente com banco principal durável. | Um sistema transacional usa SQL e quer tolerar falha de AZ; outro faz relatórios agregados de grandes conjuntos. Mesmo banco por palavra-chave SQL? | Não. RDS/Aurora atendem o transacional; Redshift atende o warehouse. O padrão de uso pesa mais que a presença de SQL.
3.8 | Em bucket de uso geral, cada objeto tem chave, conteúdo e metadados; prefixos parecem pastas. Policies controlam acesso; versões e lifecycle cuidam do ciclo de vida. | Objetos e backups: S3. Disco de SO: EBS. Sistema de arquivos compartilhado: EFS/FSx. Escolha classe por acesso, tempo de recuperação e possibilidade de recriar o dado. | S3 não executa PHP ou um servidor de aplicação. Site estático e distribuição HTTPS exigem escolhas apropriadas. Versionamento não torna exclusão impossível; Object Lock tem regras próprias. | Um site contém HTML e imagens, mas o pagamento exige lógica no servidor. S3 sozinho hospeda tudo? | Não. S3 pode guardar o conteúdo estático; a lógica precisa de computação e integração, como API Gateway com Lambda, ou servidor adequado.
3.9 | Bloco funciona como disco; arquivo usa protocolos de sistema de arquivos; objeto é acessado por API. Backup guarda pontos de recuperação; replicação para DR mantém dados preparados para recuperação. | EBS para disco de EC2; EFS para arquivos NFS compartilhados; FSx para necessidades de sistema de arquivos específico; Storage Gateway para integrar ambiente próprio ao armazenamento AWS. | EBS pertence a uma AZ e não é um compartilhamento NFS. Multi-Attach é limitado a configurações suportadas. Backup e replicação não dispensam teste de restauração. | Duas EC2 Linux em AZs diferentes precisam dos mesmos arquivos. Um único EBS atende diretamente? | Não. EFS é a opção típica de arquivos compartilhados; um EBS precisa respeitar sua AZ e condições de anexação.
3.10 | VPC fornece rede lógica; subnets e tabelas de rota definem caminhos; gateways e endpoints conectam destinos; SG/NACL controlam tráfego. DNS encontra endereços, CDN entrega conteúdo. | Route 53 para DNS; CloudFront para cache/distribuição; API Gateway para entrada de API; VPN para túnel; Direct Connect para conexão dedicada; PrivateLink para serviço privado suportado. | Subnet pública sozinha não torna EC2 acessível: precisa endereço adequado, rota, controles e aplicação. Direct Connect não cifra tudo por padrão; use criptografia quando requerida. | Uma instância privada precisa iniciar downloads na internet sem aceitar conexões iniciadas de fora. Qual componente típico? | NAT Gateway para saída IPv4 com rotas adequadas. Internet Gateway sem endereço público e sem configurar o restante não resolve sozinho.
3.11 | Dados entram por fontes/streams; Glue cataloga e transforma; Athena consulta; Redshift organiza análise em warehouse; Quick Sight apresenta resultados; OpenSearch pesquisa documentos/logs. | Observe o verbo: consultar SQL no S3, transformar, processar fluxo, executar Spark, pesquisar ou visualizar. Cada verbo aponta para uma etapa distinta. | Dashboard não coleta automaticamente todo dado. Catálogo guarda metadados, não copia necessariamente o conteúdo. Streaming e ETL não são sinônimos. | Arquivos de vendas já estão no S3 e você quer uma consulta SQL eventual, sem manter cluster. Qual serviço? | Athena. Glue Data Catalog pode descrever tabelas; Quick Sight visualiza resultados. EMR faz sentido quando o requisito é processamento com frameworks como Spark.
3.12 | Serviços prontos transformam entradas em resultados por API; SageMaker AI oferece recursos para preparar, treinar e servir modelos; Amazon Q entrega assistência conforme a variante. | Texto para voz: Polly. Voz para texto: Transcribe. Texto e sentimento: Comprehend. Documento e campos: Textract. Imagens: Rekognition. Conversação: Lex. Modelo próprio: SageMaker AI. | IA não garante resposta correta nem autorização para todo dado. Idioma, formato e região precisam ser suportados. Bedrock não citado na lista não implica automaticamente exclusão formal. | Um formulário escaneado tem tabelas e campos que precisam ser extraídos. Basta usar Comprehend? | Textract atende a extração documental; Comprehend pode analisar o texto depois. Escolha pelo tipo de entrada e pelo resultado esperado.
3.13 | SQS mantém mensagens para consumidores; SNS publica para assinantes; EventBridge filtra e roteia eventos; Step Functions controla etapas, escolhas e retentativas do fluxo. | Fila de trabalho: SQS. Aviso para vários destinos: SNS. Eventos com regras: EventBridge. Sequência com estado: Step Functions. As combinações podem ser necessárias. | Ler da fila não é o mesmo que excluir. Consumidores devem tratar repetição. SNS sozinho não dá a cada assinante uma fila persistente para consumo posterior. | Cada pedido precisa acionar faturamento e estoque, e cada equipe deve processar no próprio ritmo. Como combinar? | SNS com uma fila SQS para cada consumidor permite fan-out e desacoplamento. Uma só fila com dois consumidores normalmente distribui trabalho entre eles, em vez de entregar uma cópia para cada equipe.
3.14 | Connect organiza atendimento; SES envia e-mails; WorkSpaces entrega desktops; AppStream entrega aplicações por streaming; Secure Browser entrega navegação isolada; IoT Core conecta dispositivos. | Diferencie aplicação corporativa pronta, capacidade para executar servidor e conexão de dispositivo. Amplify ajuda a construir e implantar aplicações web/mobile. | SES não é uma caixa de e-mail de uso pessoal. Desktop remoto não é um servidor EC2 de back-end. IoT Core não instala sensores nem resolve a conectividade física do dispositivo. | Funcionários precisam de desktop completo, e clientes precisam receber confirmação por e-mail. Quais serviços? | WorkSpaces para os desktops; SES para o envio de e-mail pela aplicação. São necessidades independentes.
3.15 | CodeBuild executa build/testes; CodePipeline coordena estágios e integra ferramentas; X-Ray acompanha traces de requisições; CLI/SDK operam APIs. | Compilar: CodeBuild. Automatizar o fluxo entre etapas: CodePipeline. Investigar latência entre serviços: X-Ray. Consultar métricas/logs: CloudWatch. | Criar pipeline não escreve testes nem código. Trace depende de instrumentação e amostragem. Ferramentas fora do escopo podem ser úteis em produção sem virar foco da prova. | A equipe quer descobrir em qual serviço uma requisição demorou. O histórico de deploy sozinho resolve? | X-Ray oferece rastreamento distribuído com instrumentação apropriada. CodePipeline informa a execução da esteira, não o caminho interno da requisição.
3.16 | CloudFormation cria stacks; Systems Manager opera recursos gerenciados; Config avalia configuração; CloudWatch observa operação; Trusted Advisor recomenda; Health informa eventos AWS. | Para criar: IaC. Para executar comandos/patches: Systems Manager. Para comparar regras: Config. Para recomendações de tamanho: Compute Optimizer. Para quota: Service Quotas. | Uma recomendação não altera o recurso automaticamente. Aumentar quota não é garantia de capacidade física disponível. Agentes, roles, suporte e integração variam por ferramenta. | Você quer aplicar patches em vários servidores e consultar limites da conta. Qual ferramenta para cada tarefa? | Systems Manager Patch Manager para a operação de patch, com pré-requisitos atendidos; Service Quotas para limites e solicitações de aumento.
3.17 | Descoberta identifica servidores/dependências; avaliação estima custo; migração replica dados ou servidores; teste valida o destino; cutover muda a operação para o destino. | Servidor inteiro: Application Migration Service. Dados de banco: DMS. Conversão de esquema: SCT ou capacidade suportada de conversão. Dados de arquivos: ferramentas específicas conforme protocolo. | DMS não converte automaticamente toda lógica SQL. Replicação não dispensa rede, permissões, compatibilidade e teste. Serviço no escopo pode estar restrito a clientes existentes. | A origem é Oracle e o destino PostgreSQL. Copiar linhas com DMS basta para garantir funcionamento? | Não. Avalie conversão de esquema/código, tipos e recursos incompatíveis; DMS move dados nas condições suportadas. Valide a aplicação antes do cutover.
3.18 | Serviços especializados resolvem necessidades específicas, como grafo, Kafka ou compartilhamento de dados. A lista oficial separa os explicitamente incluídos, excluídos e não citados. | Priorize tasks e serviços incluídos; fichas mistas devem ser lidas por serviço, não por categoria inteira. Use extras para entender diferenças, sem substituir os fundamentos. | Ausência na lista não prova que nunca será cobrado. Estar fora do escopo não prova que o produto é ruim nem justifica responder sem ler o cenário. | Você reconhece Kafka em uma alternativa, mas a questão só pede streaming gerenciado no escopo. Basta escolher por popularidade? | Não. Compare requisito e opções, e priorize o serviço adequado ao escopo, como Kinesis. Fora do escopo reduz prioridade de estudo; não é uma regra universal de eliminação por nome.
4.1 | A cobrança combina unidades: tempo de computação, capacidade armazenada, requisições, processamento e transferência. Recursos relacionados podem ser cobrados separadamente. | Pay-as-you-go dá flexibilidade; compromissos podem reduzir preço para consumo previsível; classes de armazenamento trocam custo por frequência e prazo de recuperação. | Grátis para um componente não significa solução inteira gratuita. Região, plataforma, volume e modalidade alteram preços; orçamento deve incluir dependências. | Uma função Lambda barata passa por NAT Gateway e grava logs. Só estimar a função basta? | Não. Inclua rede, logs e armazenamento conforme o uso. A cobrança acompanha os recursos utilizados, não apenas o serviço principal.
4.2 | On-Demand evita compromisso longo; Spot usa capacidade disponível com possibilidade de interrupção; RIs/Savings Plans reduzem preço mediante compromisso. Reserva de capacidade atende outro objetivo. | Interrupção aceitável: Spot. Demanda incerta: On-Demand. Uso estável: avalie compromisso. Licença por hardware: Dedicated Host. Necessidade de capacidade em AZ: Capacity Reservation. | Savings Plans não reservam capacidade. RI regional e RI zonal têm comportamentos distintos. Terminar uma instância não cancela compromisso contratado. | A equipe precisa de capacidade garantida numa AZ amanhã. Um Compute Savings Plan sozinho resolve? | Não. Ele trata desconto por compromisso de gasto. Reserva de capacidade é o mecanismo adequado para a necessidade de capacidade, conforme elegibilidade e condições.
4.3 | Volume provisionado, cópias, requests e transferência geram consumo mesmo quando a aplicação principal está parada. Armazenamento arquivado pode ter permanência mínima e custo de recuperação. | Revise computação, armazenamento, rede, observabilidade e compromissos separadamente. Compare entrada/saída, entre AZs e entre regiões; consulte exceções por serviço. | Não use regras absolutas como toda transferência interna é gratuita ou parar tudo zera a conta. Free Tier depende de conta, oferta, limites e modalidade atual. | Uma equipe apaga EC2, mas mantém snapshots e objetos S3. Esses dados deixam de ser cobrados? | Não. São recursos independentes que persistem e continuam sujeitos a cobrança. Excluir a computação não exclui necessariamente cópias e dados.
4.4 | Calculator estima antes do uso; Cost Explorer investiga custo e consumo; Budgets acompanha limites e previsão; CUR/Data Exports fornece registros detalhados para análise. | Antes de implantar: Calculator. Onde gastou: Explorer. Avisar quando ultrapassar meta: Budgets. Dados detalhados: exportação. Tags de custo precisam ser ativadas conforme sua categoria. | Budgets não é um teto rígido de cobrança. Atualização de dados e ações têm latência. Colocar tag num recurso não a torna automaticamente coluna ativa dos relatórios de custo. | A empresa quer avisar ao atingir 80% do orçamento e explicar quais serviços gastaram mais. Qual combinação? | Budgets para alerta e Cost Explorer para análise. Calculator projeta uma solução; não substitui os gastos já registrados.
4.5 | Support Center organiza casos de suporte; planos determinam canais, recursos e objetivos de resposta. TAM oferece orientação técnica proativa; cobrança/conta é uma necessidade distinta de incidente técnico. | Leia o nome e o contexto: o guia consultado cita modelos clássicos; a página comercial oferece planos novos. Preserve as duas tabelas com fonte e data, sem tratar lançamento comercial como confirmação de questão. | Tempo de primeira resposta não é prazo de resolução nem SLA da aplicação. Basic não inclui atendimento técnico individual como os planos pagos. | Um plano promete primeira resposta para incidente crítico em quinze minutos. Isso garante que a aplicação será restaurada nesse prazo? | Não. O objetivo se refere ao contato inicial do suporte, sujeito aos termos; restaurar depende do diagnóstico, contexto e ações necessárias.
4.6 | Documentação explica capacidades; Knowledge Center reúne orientações; re:Post oferece comunidade; Professional Services auxilia projetos; parceiros implementam/integram; Marketplace comercializa ofertas. | Dúvida de documentação, incidente, projeto de migração, compra de produto e denúncia de abuso pedem recursos distintos. Leia o objetivo antes de escolher. | Marketplace não garante gratuidade nem que a AWS opera toda solução de terceiros. Comunidade não equivale a caso de suporte com objetivo contratual de resposta. | A empresa quer contratar software de fornecedor integrado ao processo de compra AWS. Qual recurso? | AWS Marketplace. Para ajuda em projeto de adoção, avalie Professional Services ou parceiros; para incidente, o suporte apropriado.
""", 6)

FICHAS = linhas("""
ec2 | Instância, AMI, tipo, subnet, security group, volume e role | Sistema operacional, capacidade, rede e persistência | Defina a configuração, inicie a máquina, conecte-se por método autorizado e opere a aplicação | Pode instalar software e administrar o SO; a aplicação usa role para APIs AWS | EC2 encerrada não volta a iniciar; volumes preservados e compromissos podem continuar cobrados | Servidor legado com controle de Linux: EC2; lembre que patch do SO é tarefa do cliente.
ec2-auto-scaling | Grupo, launch template, mínimo, máximo, capacidade desejada e políticas | Número de instâncias e critérios de saúde/escala | O grupo compara saúde e demanda com a configuração e ajusta instâncias | Pode recuperar capacidade e distribuir instâncias entre AZs configuradas | Não remove gargalos de aplicação/banco nem copia arquivos locais entre instâncias | Pico previsível: política agendada; demanda variável: política dinâmica com métrica adequada.
elastic-load-balancing | Load balancer, listeners, target groups, destinos e health checks | Tipo, protocolo, portas, certificados e destinos | Recebe conexão, aplica regra de listener e encaminha para destino saudável | ALB permite regras HTTP; NLB atende necessidades de transporte | Não executa aplicação nem aumenta capacidade sozinho | Dois caminhos de uma aplicação web vão para serviços diferentes: regras por caminho no ALB.
lambda | Função convencional, código, runtime, execution role, trigger e logs | Memória, timeout, concorrência, VPC e tratamento de falha | Evento invoca a função; código usa permissões da role e devolve ou grava resultado | Executa lógica sem administrar hosts; memória/código local não são armazenamento durável garantido | Limite de quinze minutos é por invocação convencional; recursos como MicroVMs e Durable Functions têm modelos próprios | Miniatura após upload: evento S3 invoca função que precisa de leitura/gravação e logs autorizados.
ecs | Cluster, task definition, task, service e capacidade | Imagem, CPU/memória, role, rede, número de tasks e capacidade EC2/Fargate | A definição descreve containers; o service mantém tasks; capacidade executa | Pode operar containers de longa duração ou tarefas pontuais | ECS não é registro de imagens; criar cluster não publica uma API automaticamente | Web containerizada sem administrar hosts: ECS com Fargate, com rede e exposição configuradas.
eks | Cluster Kubernetes, control plane, pods, services e capacidade | Versão, acesso, rede e modalidade de execução dos workloads | Envie manifests; Kubernetes agenda workloads na capacidade configurada | Fornece Kubernetes gerenciado e integrações AWS | Gerenciar control plane não elimina configuração dos workloads e responsabilidades da modalidade escolhida | Equipe exige APIs Kubernetes: EKS, em vez de escolher ECS apenas porque ambos executam containers.
fargate | Tasks ECS ou workloads EKS compatíveis e interfaces de rede | Recursos de CPU/memória suportados, imagem, roles e rede | Orquestrador solicita capacidade; Fargate executa container sem você manter o host | Reduz administração dos servidores de containers | Não armazena imagens nem substitui ECS/EKS; aplicações ainda exigem segurança e dados persistentes adequados | Container de worker: ECR guarda imagem, ECS organiza, Fargate executa.
ecr | Repositório, imagens, tags/digests e políticas | Acesso, retenção/lifecycle e opções de varredura | Faça push da imagem e autorize o ambiente de execução a fazer pull | Distribui artefatos de container e pode integrar varredura | Guardar imagem não inicia container; imagem pode conter bibliotecas vulneráveis | Versionar imagem de API: ECR; iniciar API: serviço de execução, como ECS.
elastic-beanstalk | Application, versions, environment e recursos provisionados | Plataforma, versão de código, variáveis, escala e rede | Envie versão; o ambiente implanta e acompanha recursos da aplicação | Simplifica deploy sem impedir acesso aos recursos subjacentes autorizados | Aplicação, dependências e configurações continuam com o cliente; recursos usados são cobrados | Enviar aplicação web e delegar provisionamento comum: Beanstalk, sem presumir custo zero.
lightsail | Instâncias, discos, snapshots e recursos simplificados | Blueprint, bundle, rede e backups | Crie pacote, instale/configure aplicação e acompanhe consumo | Oferece início simples com preço de pacote e limites descritos | Não significa capacidade ilimitada ou proteção automática da aplicação | Pequeno site com requisitos simples: Lightsail; requisitos complexos pedem avaliar EC2 e serviços especializados.
batch | Job definition, job queue, compute environment e jobs | Container/comando, recursos, prioridade, tentativas e capacidade | Envie job para fila; Batch agenda em capacidade compatível | Organiza processamento em lotes e dependências entre jobs | Não é serviço de resposta HTTP contínua nem fornece computação gratuita | Processar simulações independentes: jobs Batch, com resultados persistidos fora da execução efêmera.
outposts-local-zones-wavelength | Outposts no local do cliente; Local Zones próximas de cidades; Wavelength junto à rede de operadoras | Localidade, serviço disponível e infraestrutura/conectividade exigida | Selecione oferta pelo requisito de localização e use recursos compatíveis | Outposts atende workloads locais com serviços AWS suportados | Não oferece todo o catálogo em qualquer local; os três nomes têm status de escopo diferentes | Requisito de manter computação no prédio: avalie Outposts; não confunda com região inteiramente nova.
s3 | Bucket de uso geral, objetos, chaves, versões, policies e lifecycle | Região, acesso, criptografia, versionamento e classes | Grave objeto por API e recupere pela chave com autorização | Guarda arquivos de qualquer tipo; site estático é possível | Não executa back-end; limite de upload varia por método: PUT simples 5 GB, console 160 GB, multipart até 50 TB | PDF privado por tempo limitado: URL pré-assinada; ela não torna todo o bucket público.
s3-classes-de-armazenamento | Classes/camadas de objeto, regras lifecycle e solicitações de restore | Frequência, prazo de acesso, permanência mínima e tolerância a uma AZ | Escolha classe ou lifecycle; quando necessário, restaure objeto arquivado antes do uso | Reduz custo de dados pouco acessados conforme condições da classe | Glacier Instant Retrieval não requer espera de restore como Flexible/Deep Archive; uma AZ reduz resiliência a perda da AZ | Arquivo raro que deve abrir imediatamente: Glacier Instant Retrieval; espera de horas permite outras classes.
ebs | Volume de bloco, anexação à EC2, tipos de volume e snapshots | AZ, capacidade, desempenho, criptografia e DeleteOnTermination | Crie na AZ compatível, anexe, formate/use; snapshots geram pontos de recuperação | Pode persistir dados além da vida da EC2 se configurado para preservação | Não é sistema de arquivos NFS multi-AZ; Multi-Attach tem requisitos específicos | Disco do SO de EC2: EBS; arquivos compartilhados em AZs distintas: avalie EFS.
efs | Sistema de arquivos, mount targets, access points e classes | Rede NFS, permissões, modalidade regional/uma zona e lifecycle | Crie pontos de montagem e monte nos clientes autorizados | Compartilha arquivos entre clientes Linux compatíveis | Precisa de conectividade e autorização de rede/arquivo; não é disco de boot EC2 | Vários servidores web Linux usam o mesmo conteúdo: EFS, com configuração dos mounts.
fsx | Famílias de sistemas de arquivos gerenciados e endpoints | Família, protocolo, capacidade e opções de disponibilidade | Escolha pelo sistema/protocolo exigido e conecte os clientes | Atende necessidades como arquivos Windows/SMB com a família apropriada | Cada família tem capacidades distintas; FSx for Lustre está explicitamente fora do escopo consultado | Aplicação Windows exige SMB e integração AD: avalie FSx for Windows File Server.
storage-gateway | Gateway no ambiente do cliente, cache local e armazenamento AWS | Modalidade de arquivos, volumes ou fitas e capacidade local | Aplicação usa protocolo compatível; gateway integra o armazenamento remoto | Permite adoção híbrida mantendo interfaces familiares | Não é migração instantânea de toda aplicação; precisa host, cache e conectividade conforme modalidade | Sistema de backup usa interface de fita: Tape Gateway, em vez de reescrever o sistema para API S3.
aws-backup | Planos, seleções de recursos, vaults e recovery points | Agenda, retenção, cópias, permissões e recursos elegíveis | Associe recursos ao plano, acompanhe jobs e teste restauração | Centraliza políticas de backup para serviços suportados | Não inclui automaticamente todo recurso e não substitui disponibilidade ou teste de recuperação | Políticas comuns de retenção entre serviços: AWS Backup, com seleção e proteção configuradas.
elastic-disaster-recovery | Servidores origem, agente, área de staging e recovery instances | Rede de replicação, destino e configuração de lançamento | Replica blocos, permite testes e lança recuperação quando necessária | Ajuda a reduzir perda de dados e tempo de recuperação de servidores compatíveis | RTO/RPO dependem do ambiente; replicação não substitui backup histórico | Recuperar servidores após desastre: DRS; migrar definitivamente: avalie a ferramenta de migração.
rds | DB instance/cluster, engine, endpoint, subnet group, SG e backups | Motor, tamanho, armazenamento, acesso, backup e disponibilidade | Provisione banco e conecte aplicação ao endpoint autorizado | Administra SO e tarefas comuns; cliente administra esquema, consultas e acesso | RDS convencional não entrega acesso root irrestrito ao host; Multi-AZ DB instance standby não atende leituras | Alta disponibilidade: Multi-AZ; aliviar consultas: read replicas compatíveis, distinguindo modalidades de cluster.
aurora | Cluster, writer, readers, endpoints e armazenamento compartilhado | Compatibilidade MySQL/PostgreSQL, capacidade e disponibilidade | Aplicação escreve no writer e pode distribuir leituras aos readers | Oferece banco relacional gerenciado com arquitetura própria | Não é engine compatível com qualquer banco SQL; endpoints e opções dependem da configuração | Relacional compatível MySQL com leitores: Aurora; não confunda reader com writer.
dynamodb | Tabelas, itens, atributos, partition key, sort key opcional e índices | Chave, modo de capacidade, backups, streams e replicação | Aplicação usa APIs orientadas à chave e consultas compatíveis | Entrega chave-valor/documentos sem administrar servidores | Não funciona como relacional com joins arbitrários; escolha de chave influencia distribuição e consultas | Sessão de usuário acessada pelo identificador: DynamoDB pode servir; consultas relacionais complexas apontam para outro modelo.
elasticache | Cache, motores suportados, endpoints e política de expiração | Motor, capacidade, rede e estratégia de cache | Aplicação consulta cache; no miss, busca origem e preenche conforme estratégia | Reduz latência e consultas repetitivas ao banco principal | Não acelera automaticamente código que nunca usa o cache; não trate toda modalidade como armazenamento definitivo | Resultado muito consultado: cache com TTL; aplicação deve tratar expiração e indisponibilidade.
memorydb | Banco compatível com APIs Redis/Valkey conforme oferta, shards e réplicas | Motor, capacidade, acesso e disponibilidade | Aplicação acessa dados em memória com mecanismos de durabilidade do serviço | Pode servir como banco principal para workloads compatíveis | Está fora do escopo consultado; cache e banco durável não têm o mesmo objetivo | Necessidade de banco durável de baixa latência difere de cache descartável; preserve essa diferença sem priorizar na CLF-C02.
redshift | Warehouse, tabelas, endpoints e modalidades provisionada/serverless | Capacidade, dados, acesso e carregamento/consulta | Ingestão organiza dados para análise SQL; ferramentas consultam e visualizam | Prioriza grandes análises e agregações | Não é a escolha típica de transação individual de aplicação OLTP | Agregar anos de vendas: Redshift; processar cada venda do caixa: banco transacional apropriado.
documentdb | Cluster de documentos, instâncias, endpoints e índices | Versão/API compatível, rede, capacidade e backup | Aplicação usa driver/operações compatíveis para guardar e consultar documentos | Atende modelo documental com compatibilidade anunciada com MongoDB | Compatibilidade não garante todos os recursos ou comportamento do MongoDB | Migrar aplicação documental: valide as operações usadas; não suponha migração sem teste só por usar driver semelhante.
neptune | Banco de grafos, vértices/arestas ou triplas e endpoints | Modelo e linguagem de consulta compatíveis, capacidade e acesso | Modele relações e percorra conexões com consultas de grafo | Ajuda a explorar redes de relações complexas | Não é sinônimo de dashboard nem banco relacional tradicional | Descobrir relações entre pessoas e contas para fraude: grafo com Neptune.
keyspaces-timestream-e-outros | Bancos especializados por API/modelo, como Cassandra e séries temporais | Tipo de dado, API compatível e oferta disponível | Escolha banco pelo modelo de acesso antes de migrar dados | Serviços especializados podem reduzir gestão de infraestrutura | Keyspaces está fora do escopo; Timestream não citado não deve ser tratado como exclusão formal | Dados de sensores com tempo como dimensão pedem modelo temporal; popularidade não substitui requisito.
vpc | CIDR, subnets, rotas, gateways, endpoints, SGs e NACLs | Faixas de IP, AZs, caminhos e controles de rede | Crie rede e subnets; associe rotas e controles; conecte recursos | Isola logicamente a rede e permite conectividade pública/privada planejada | SG aberto não cria rota; subnet pública não fornece endereço público automaticamente a toda carga | EC2 pública IPv4 exige rota ao IGW, endereço apropriado, regras e aplicação escutando.
vpc-peering-transit-gateway-e-endpoints | Peering entre VPCs; hub Transit Gateway; endpoints e PrivateLink | Redes envolvidas, rotas, serviço exposto e permissões | Escolha conexão de redes ou acesso privado a serviço e configure ambos os lados | TGW atende topologia hub; PrivateLink expõe serviços compatíveis sem abrir conectividade inteira | Peering não é transitivo; endpoint não substitui IAM | Três redes precisam comunicação por hub: TGW; consumidor só precisa de serviço privado: PrivateLink.
site-to-site-vpn-e-client-vpn | Túneis Site-to-Site entre redes; endpoint Client VPN para usuários | Endereços, autenticação, rotas e regras de autorização | Estabeleça túnel/conexão e permita destinos específicos | Fornece conectividade criptografada nas modalidades apropriadas | Não torna toda rede acessível sem rotas e autorização; Site-to-Site não é cliente remoto individual | Filial inteira: Site-to-Site VPN; funcionário remoto individual: Client VPN.
direct-connect | Conexão, interfaces virtuais e gateways associados | Localidade, banda, conexão e redundância | Conecte o ambiente próprio à AWS por caminho dedicado e configure roteamento | Ajuda a ter conectividade privada e características previsíveis | Criptografia não é automática em toda modalidade; resiliência exige planejamento | Conexão dedicada de datacenter: Direct Connect; criptografia adicional pode usar VPN conforme requisito.
route-53 | Hosted zones, records, health checks e políticas de roteamento | Domínio, registros, TTL e política | DNS devolve o endereço conforme registros e política | Pode registrar domínios, resolver nomes e rotear respostas DNS | DNS não transporta nem balanceia cada pacote da sessão como um load balancer | Usuários encontram o endereço do site: Route 53; distribuição de conteúdo: CloudFront.
cloudfront | Distribution, origins, behaviors, cache e políticas | Origem, HTTPS, cache, acesso e caminhos | Usuário acessa edge; cache responde ou busca a origem | Distribui conteúdo estático/dinâmico com mecanismos de cache | Não substitui back-end; resposta pode permanecer em cache até atualização/invalidation; OAC não serve ao website endpoint S3 | Conteúdo privado S3 com HTTPS: origem S3 apropriada e OAC, sem tornar bucket público.
global-accelerator | Accelerator, IPs estáticos, listeners, endpoint groups e endpoints | Protocolo, regiões, saúde e pesos | Recebe conexão na borda e encaminha pela rede AWS ao endpoint elegível | Melhora caminhos para aplicações TCP/UDP globais | Não é cache/CDN de objetos e não substitui a aplicação | Usuários globais precisam IPs fixos e tráfego TCP/UDP: Global Accelerator, em vez de escolher CloudFront por palavra global.
api-gateway | API, routes/resources, stages, integrações e autorização | Tipo de API, endpoint, autenticação, throttling e integração | Recebe requisição e chama back-end conforme rota | Publica e gerencia entrada de APIs sem administrar servidores de gateway | Não implementa a regra de negócio sozinho; autorização ainda precisa ser configurada | API chama função Lambda: API Gateway oferece entrada; Lambda executa lógica; IAM/authorizer controla acesso.
iam | Usuários, grupos, roles e policies | Actions, resources, conditions e identidade confiável | Identidade autentica; avaliação de políticas autoriza ou nega ação | Oferece menor privilégio e credenciais temporárias via roles | Policy é permissão, não conexão de rede; Deny explícito prevalece nos contextos aplicáveis | Aplicação EC2 lê S3 com role; permissões e rede continuam requisitos distintos.
iam-identity-center | Diretório/IdP, usuários/grupos, permission sets e assignments | Origem de identidade, contas, aplicações e permissões | Usuário entra no portal e assume acesso atribuído | Centraliza acesso de força de trabalho a contas/apps | Não é cadastro de consumidores de uma aplicação pública; atribuição não ignora SCP | Funcionários em várias contas: Identity Center; clientes do app: Cognito.
cognito | User pools, app clients e identity pools | Métodos de login, federação, MFA e roles | User pool autentica; identity pool pode trocar identidades por credenciais AWS | Permite login de consumidores e acesso autorizado a recursos | User pool e identity pool não são o mesmo recurso; login não concede toda ação AWS | App precisa login social e acesso limitado a recurso: combine capacidades conforme requisito.
directory-service | Diretórios gerenciados/conectores e integração de rede | Tipo de diretório, DNS, rede e trusts suportados | Conecte workloads ao diretório para autenticação compatível | Integra necessidades de Active Directory ao ambiente AWS | AD Connector não equivale a criar nova cópia de diretório gerenciado | Aplicação Windows precisa AD: avalie modalidade correta, em vez de presumir que IAM substitui qualquer protocolo de diretório.
kms | Chaves, aliases, key policies e grants | Tipo, administradores, usuários, rotação e integração | Serviço/aplicação solicita operação criptográfica autorizada | Protege chaves e integra criptografia a serviços como EBS e S3 | Rotacionar chave não recriptografa automaticamente todos os dados; remover acesso pode impedir leitura | SSE-KMS: permissão S3 sem autorização na chave pode falhar ao ler objeto.
cloudhsm | Cluster HSM, usuários criptográficos e clientes | Quantidade/localização, usuários e gerenciamento de chaves | Cliente conecta ao HSM e usa APIs criptográficas suportadas | Oferece hardware dedicado e maior controle operacional de chaves | Cliente mantém responsabilidades de usuários/chaves; não é simples cofre de senha | Requisito de HSM dedicado com controle de chaves: CloudHSM; integração simples de chave gerenciada: KMS.
certificate-manager | Certificados, validação de domínio e associação a serviços | Domínios, tipo de certificado e serviço/região | Solicite/importe, valide e associe ao endpoint compatível | Facilita TLS em serviços integrados | Renovação/uso depende da modalidade; certificado não autoriza leitura de dados | HTTPS no ALB: certificado ACM; criptografar volume EBS: chave KMS.
secrets-manager-e-parameter-store | Secrets e parâmetros; versões e chaves de criptografia quando aplicável | Acesso, valor, rotação e integração | Aplicação busca valor com identidade autorizada; rotação depende de configuração suportada | Separa segredo/configuração do código | Não basta criar segredo: aplicação precisa usá-lo; rotação não muda magicamente sistemas sem integração | Senha de banco com rotação: Secrets Manager; parâmetros comuns: avalie Parameter Store.
shield | Proteção Standard e assinatura Advanced para recursos elegíveis | Recursos protegidos e recursos extras contratados | Proteção e mitigação atuam contra ataques DDoS conforme cobertura | Standard cobre proteção básica; Advanced acrescenta capacidades e apoio | Não equivale a filtro de SQL injection nem corrige vulnerabilidades no código | Ataque volumétrico: Shield; requisição HTTP maliciosa: WAF pode complementar.
waf | Web ACL, rules, rule groups e associação a recursos | Critérios HTTP, rate-based rules, ação e logging | Requisição é avaliada pelas regras antes de seguir ao recurso | Pode permitir, bloquear ou contar conforme regras e suporte | Não é firewall universal de toda EC2 nem corrige a causa no código | SQL injection em aplicação web suportada: WAF; modo Count ajuda a avaliar regra antes de bloquear.
firewall-manager-e-network-firewall | Políticas centralizadas do Firewall Manager; endpoints/regras de Network Firewall | Escopo de contas/recursos e regras | Defina políticas comuns e aplique a recursos elegíveis com pré-requisitos | Firewall Manager reduz repetição de administração entre contas | Não são o mesmo produto; Network Firewall está fora do escopo consultado | Mesma política WAF em várias contas: Firewall Manager, com Organizations e configuração necessária.
guardduty | Detector, fontes de dados/proteções e findings | Região, contas, proteções e destinatários de achados | Analisa sinais e gera findings; resposta é operada ou automatizada à parte | Identifica comportamento potencialmente malicioso | Detectar não garante bloquear ou corrigir sozinho | Credenciais usadas de forma suspeita: GuardDuty; pacote com CVE: Inspector.
inspector | Recursos elegíveis, cobertura de varredura e findings | Cobertura, acesso e pré-requisitos conforme recurso | Inspeção identifica vulnerabilidades e exposição conforme modalidade | Ajuda a priorizar correções de software em EC2/ECR/Lambda suportados | Não substitui patch nem cobre automaticamente qualquer recurso da conta | Dependência vulnerável numa imagem: Inspector integrado à varredura adequada; equipe corrige e republica.
macie | Inventário de buckets, jobs, identificadores e findings | Buckets, escopo, formatos e identificadores suportados | Inspeciona dados elegíveis no S3 e reporta dados sensíveis/postura | Pode encontrar padrões de informação pessoal ou segredos | Não varre genericamente RDS/EBS e não apaga conteúdo sensível sozinho | Encontrar dados pessoais em documentos S3: Macie; confirme elegibilidade do formato e permissões.
detective | Behavior graph e investigação de entidades/eventos | Conta, região, fontes e acesso | Agrega contexto para explorar relações em atividade suspeita | Ajuda investigação após sinais ou achados | Não é firewall ou substituto automático da detecção/remediação | Após finding GuardDuty, investigar contexto: Detective; bloquear requer ação apropriada.
security-hub | Findings, controles/standards, agregação e configuração de contas | Padrões, regiões, contas e integrações | Recebe achados e avalia controles compatíveis; equipe prioriza resposta | Centraliza visão de postura e problemas | Agregação não significa correção automática de cada finding nem certificação de conformidade | Ver achados de vários serviços num lugar: Security Hub; identificar PII em S3: Macie produz o achado.
artifact | Relatórios e agreements | Documento solicitado e autorização para consulta | Localize e obtenha evidência oficial da AWS | Ajuda a demonstrar controles da infraestrutura AWS | Não registra atividade de usuários da sua conta nem certifica sua aplicação | Auditor pede relatório AWS: Artifact; quem apagou recurso: CloudTrail.
audit-manager | Frameworks, assessments, controls e evidências | Escopo de avaliação e responsáveis | Coleta/organiza evidências e permite revisão humana | Ajuda preparação de auditoria conforme disponibilidade do serviço | Não decide conformidade legal automaticamente; observe restrição a novos clientes indicada na ficha | Evidência da conta do cliente difere de relatório da AWS: Audit Manager e Artifact têm papéis distintos.
cloudwatch | Métricas, logs, alarmes e dashboards | Coleta, retenção, thresholds e ações | Recurso/agente envia dados; alarme avalia condição e pode acionar integração | Observa saúde operacional e tendência | Memória de EC2 não vem toda por padrão; alarme sem ação não remedia nada | CPU acima da meta: métrica/alarme; quem mudou SG: CloudTrail.
cloudtrail | Eventos de gerenciamento/dados, event history e trails | Cobertura, regiões, destino e retenção | Operações elegíveis geram eventos; histórico/trail permite consulta e armazenamento | Ajuda a investigar identidade e ação executada | Eventos de dados têm configuração própria; não é histórico infinito gratuito de todo acesso | Descobrir quem alterou IAM: CloudTrail; gravar trilha e retenção conforme auditoria.
config | Recorder, configuration items, rules e aggregators | Tipos de recurso, cobertura e regras | Registra configuração e avalia conformidade com critérios | Mostra mudanças de estado/configuração de recursos suportados | Avaliar regra não bloqueia necessariamente criação; remediação depende de integração | Saber se bucket atende regra e seu estado anterior: Config; quem mudou: CloudTrail.
systems-manager | Managed nodes, Session Manager, Run Command, Patch Manager e Automation | Agente/conectividade/role e documentos de operação | Registre o nó e use capacidade operacional autorizada | Permite comandos, sessões e patches em recursos elegíveis | Session Manager exige pré-requisitos; fechar SSH não dispensa configuração do serviço | Operar EC2 sem porta 22 aberta: Session Manager com agente, role e endpoints/rede adequados.
cloudformation | Template, stack, parameters, outputs e change sets | Recursos, dependências, permissões e tratamento de atualização | Template define recursos; stack cria/atualiza; eventos mostram resultado | Reproduz ambientes declarativamente | Deletar stack pode apagar recursos salvo proteção/retenção configurada; rollback não recupera todo dado | Recriar rede e aplicação em teste: template versionado; valide change set antes de atualização sensível.
organizations | Organização, management account, member accounts, OUs e policies | Estrutura, controles e compartilhamento de benefícios de cobrança | Organize contas e aplique políticas aos escopos apropriados | Oferece governança e faturamento consolidado | SCP não concede permissão; dados e redes das contas não se fundem | Limitar serviços nas contas membro: SCP junto com permissões IAM necessárias.
control-tower | Landing zone, contas compartilhadas, OUs e controls | Contas/regiões governadas e controles | Estabeleça baseline e acompanhe conformidade dos ambientes inscritos | Automatiza partes da configuração de governança multi-conta | Não substitui Organizations nem toda política específica da empresa | Criar base padronizada para novas contas: Control Tower, com responsabilidades de governança continuadas.
service-catalog-e-ram | Portfolios/products/constraints no Catalog; resource shares no RAM | Produto aprovado ou recurso compartilhável e destinatários | Catalog provisiona produto autorizado; RAM compartilha recurso suportado | Evita configurações repetidas e distribui recursos conforme permissões | Compartilhar não transfere propriedade nem permite qualquer tipo de recurso | Catálogo de stacks aprovadas: Service Catalog; compartilhar subnet compatível: RAM.
trusted-advisor | Checks, recomendações e visão de resultados | Conta, plano e acesso aos checks | Analise recomendações e aplique mudanças após avaliar impacto | Ajuda custos, performance, segurança e outros temas de boas práticas | Não é garantia de aplicação perfeita nem alteração automática de toda recomendação | Recomendação geral de boas práticas: Trusted Advisor; tamanho por uso observado: Compute Optimizer.
health-dashboard | Eventos públicos e eventos específicos da conta | Conta, região, serviço e integrações de evento | Consulte impacto/avisos da infraestrutura e planeje ação | Mostra ocorrências AWS e manutenção relevante | Ausência de evento AWS não prova que o código da aplicação está saudável | Manutenção de recurso específico: Health; erro interno do app: logs/métricas da aplicação.
compute-optimizer-service-quotas-e-license-manager | Recomendações, quotas e configurações de licenças | Opt-in/métricas, quota ajustável e regra de licença | Analise dimensionamento, solicite quota ou acompanhe uso de licença | Resolve três necessidades diferentes de otimização/governança | Quota não garante capacidade disponível; License Manager não compra licença | Instância grande demais: Compute Optimizer; limite da conta: Service Quotas; direito comercial: contrato da licença.
athena | Workgroups, consultas, catálogo e local de resultados | Dados, schema, formato, permissão e configurações do workgroup | Defina tabela sobre dados e execute consulta; resultados têm destino | Consulta SQL sobre dados suportados sem manter cluster | Não é banco OLTP nem deixa leitura de todo arquivo gratuita; otimizar leitura pode reduzir custo | Consultar logs S3 eventualmente: Athena com catálogo/resultado autorizados.
glue | Data Catalog, crawlers, jobs e workflows | Fonte, schema, script, role e capacidade | Crawler descreve dados; job transforma; catálogo atende motores de consulta | Oferece integração e ETL gerenciado | Catálogo não contém necessariamente os arquivos; crawler não faz sozinho a transformação de negócio | Padronizar arquivos antes da análise: Glue job; consultar dados: Athena.
kinesis | Streams, producers, consumers e oferta Firehose associada | Capacidade, retenção e destinos conforme produto | Produtores publicam; consumidores processam fluxo ou entrega agrupa dados para destino | Atende ingestão contínua e processamento de streaming | Kinesis não é apenas notificação por e-mail; produtos da família têm funções distintas | Telemetria contínua: Data Streams para consumidores; Firehose para entrega suportada com buffering.
emr | Frameworks como Spark/Hadoop e modalidades de execução | Framework, jobs, capacidade e dados | Submeta processamento distribuído em infraestrutura/modalidade apropriada | Executa frameworks de big data gerenciados | Não é ferramenta de dashboard e ainda exige configuração do job | Equipe já usa Spark para transformar grandes dados: EMR; SQL eventual no S3: Athena.
quicksight | Data sources, datasets, analyses e dashboards | Conexão, atualização, permissões e compartilhamento | Conecte dados, modele visualização e publique dashboard autorizado | Entrega BI para usuários e aplicações conforme modalidade | Não é ferramenta principal de ETL nem acesso irrestrito de qualquer usuário | Gerentes precisam gráficos de vendas: Quick Sight sobre uma fonte preparada.
opensearch | Índices, documentos e domínios/collections conforme modalidade | Ingestão, indexação, capacidade e acesso | Dados são indexados para busca/agregação e exploração | Atende pesquisa e analytics de logs/documentos | Não substitui automaticamente sistema transacional de registros | Busca por texto em catálogo: OpenSearch; transações de compra: banco apropriado.
lake-formation-msk-e-outros | Governança de lake, brokers Kafka e serviços de troca/integração de dados | Requisito e status individual no escopo | Selecione por governança, streaming compatível, compra ou integração | Cada oferta resolve uma parte da plataforma de dados | Vários nomes estão fora do escopo; não generalize capacidades/autorizações entre produtos | Kafka gerenciado é MSK; streaming no foco CLF-C02 inclui Kinesis. Compatibilidade Kafka é requisito diferente.
sagemaker-ai | Preparação, treinamento, modelos, endpoints e jobs | Dados, algoritmo, infraestrutura, acesso e modalidade de inferência | Prepare dados, treine/avalie e disponibilize inferência | Permite construir e operar modelos próprios | Não substitui dados de qualidade e validação; endpoint ativo pode gerar custo mesmo ocioso | Treinar modelo da empresa: SageMaker AI; converter texto em voz sem treino próprio: Polly.
bedrock | Modelos fundacionais, invocação e capacidades como bases/guardrails | Modelo, acesso, dados e integração suportada | Aplicação chama modelo e combina capacidades conforme necessidade | Simplifica uso de modelos fundacionais sem administrar sua infraestrutura base | Não citado na lista não significa exclusão formal; resposta exige avaliação e controle de dados | Usar modelo fundacional difere de treinar modelo próprio; explique o objetivo antes de escolher.
amazon-q | Variantes voltadas a desenvolvimento e ao uso de informações de negócio | Variante, identidades, fontes e permissões | Configure acesso e contexto apropriados; usuário recebe assistência | Ajuda em código/tarefas ou busca contextual conforme variante | Não é um único banco com acesso automático a todos os documentos da empresa | Apoio ao desenvolvedor: Q Developer; informações de negócio dependem da variante e das fontes autorizadas.
servicos-de-ia-prontos | APIs especializadas com entradas como texto, áudio, imagem e documento | Serviço, idioma/formato, processamento e acesso | Envie entrada compatível e trate o resultado na aplicação | Polly fala; Transcribe transcreve; Translate traduz; Textract extrai documentos; Rekognition analisa imagens; Lex conversa; Comprehend analisa texto | Nenhum cobre todo tipo de IA nem garante acerto; serviços extras na ficha têm escopo próprio | Áudio para texto: Transcribe; texto para áudio: Polly. Inverter a direção muda a resposta.
sqs | Fila, mensagens, produtores, consumidores e DLQ | Standard/FIFO, retenção, visibility timeout e redrive | Envie, receba, processe e exclua após sucesso | Amortece picos e desacopla execução | Receber não exclui; falha/timeout pode tornar mensagem visível novamente; efeitos de negócio precisam ser idempotentes | Worker falha após leitura: mensagem pode reaparecer; trate repetição e DLQ configurada.
sns | Topic, publishers, subscriptions e filtros | Destinos, acesso, filtros e tratamento de falha | Publique uma vez; SNS distribui a assinantes elegíveis | Faz fan-out e notificações | Não é fila persistente individual de cada consumidor; use SQS quando necessário | Pedido notifica estoque e cobrança: topic com filas independentes permite cada equipe consumir no próprio ritmo.
eventbridge | Event buses, rules, targets; Scheduler e Pipes conforme necessidade | Padrão de evento, destinos, role e falhas | Evento entra no bus, regra filtra e destino recebe | Integra eventos AWS, apps e fontes compatíveis | Não executa lógica de negócio por si; evento exige consumidor/destino | Mudança de estado dispara automação: regra EventBridge com destino autorizado.
step-functions | State machine, states, execution e integrações | Sequência, branches, retries, catches e modalidade | Execução percorre etapas e trata resultados/falhas conforme definição | Coordena processos com estado e chamadas a serviços | Não transforma todo código longo numa única função convencional sem limite | Pedido exige validar, cobrar e confirmar: fluxo coordena etapas; cada tarefa mantém seus próprios limites.
amazon-mq | Broker, filas/tópicos e engines/protocolos compatíveis | ActiveMQ/RabbitMQ, capacidade, rede e acesso | Clientes usam protocolo compatível e broker gerenciado | Ajuda migração de sistemas dependentes de brokers tradicionais | Não listado não é exclusão formal; escolha por compatibilidade, sem igualar a API SQS | Aplicação exige protocolo de broker existente: avalie MQ; nova fila AWS simples: SQS.
cli-sdk-e-cloudshell | Console, comandos CLI, bibliotecas SDK e ambiente CloudShell | Credenciais temporárias, região, serviço e operação | Interface solicita uma API com a identidade autenticada | Permite operação manual/programática com as mesmas regras de autorização | CloudShell não concede privilégio extra e está fora do escopo; SDK permanece conceito do guia | Automatizar no Python: SDK; operar por terminal: CLI; reproduzir infraestrutura: IaC.
code-services | Build projects, pipelines e estágios; ferramentas adicionais da esteira | Código fonte, comandos, artefatos, role e integrações | Pipeline coordena; Build compila/testa; ferramenta apropriada faz deploy | Automatiza fases repetíveis de entrega | Build não escreve testes; Pipeline não é repositório nem executa todo estágio sozinho | Compilar e rodar testes: CodeBuild; coordenar fluxo completo: CodePipeline.
x-ray | Traces, segments, subsegments e mapa de serviços | Instrumentação, amostragem e envio autorizado | Requisições instrumentadas produzem traces entre componentes | Ajuda localizar latência e erros no caminho distribuído | Sem instrumentação não há trace completo; não registra automaticamente toda requisição sem amostragem | Latência entre API e banco: X-Ray; tendência de CPU: CloudWatch.
amazon-connect | Instância, contact flows, queues, routing profiles e agentes | Canais, atendimento, gravação e integrações | Contato entra no fluxo e é encaminhado ao atendimento configurado | Oferece contact center gerenciado | Não substitui equipe de atendimento nem autoriza automaticamente gravações/uso de dados | Criar central de atendimento: Connect; envio transacional de e-mail: SES.
ses | Identidades verificadas, envio SMTP/API e eventos | Domínio/remetente, acesso, limites e saída do sandbox | Aplicação envia mensagem; serviço reporta entrega/bounce conforme configuração | Envia e-mails transacionais e de campanha nas condições da oferta | Sandbox restringe envio; verificar domínio não garante entrega na caixa principal | Confirmação de compra por e-mail: SES; caixa de entrada pessoal não é o objetivo principal.
workspaces-e-appstream | Desktops WorkSpaces, fleets/stacks AppStream e portal Secure Browser | Identidade, rede, imagem e regras de sessão | Usuário autentica e recebe desktop, aplicação ou navegador remoto | Entrega experiência remota sem instalar toda carga no dispositivo | São produtos distintos; persistência depende da modalidade; políticas de cópia/download devem ser configuradas | Desktop completo: WorkSpaces; app específico: AppStream; navegação isolada: Secure Browser.
amplify-e-appsync | Aplicação/hosting/build do Amplify e API GraphQL do AppSync | Código, domínio, autenticação e integrações | Implante front-end e conecte back-end conforme configuração | Amplify facilita construir/implantar web/mobile; AppSync oferece API GraphQL | Hosting não escreve regra de negócio; AppSync não aparece na lista consultada | Publicar front-end com integração AWS: Amplify; requisito específico GraphQL: entender AppSync como complemento.
iot-core-e-greengrass | Dispositivos, certificados, policies, topics e regras; runtime local Greengrass | Identidade do dispositivo, protocolo, topics e destinos | Dispositivo autentica, publica/recebe e regra encaminha dados | IoT Core conecta dispositivos; Greengrass atende execução local compatível | Não fornece conectividade física; Greengrass está fora do escopo consultado | Sensor envia telemetria com identidade própria: IoT Core; processamento local tem necessidade distinta.
discovery-migration-hub-e-evaluator | Inventário/dependências, avaliações e acompanhamento de migração | Fontes, acesso e disponibilidade de cada produto | Descubra o que existe, estime cenário e acompanhe progresso | Apoia planejamento e visibilidade | Planejar/acompanhamento não move toda carga; produtos podem estar fechados a novos clientes | Mapear dependências antes de mover servidores: Discovery; custo do cenário: Evaluator.
application-migration-service | Servidores origem, replicação, staging e launch settings | Rede, agente, destino, teste e cutover | Replica servidor compatível, lança teste e depois destino definitivo | Apoia rehost de servidores | Não refatora aplicação nem elimina teste; nomes comerciais podem mudar | Mover servidor como está: Application Migration Service; copiar banco e converter esquema: outras ferramentas.
dms-e-sct | Endpoints, tarefas de migração/replicação e conversão de esquema | Origem/destino suportados, rede, full load/CDC e mapeamentos | Prepare esquema, carregue dados e replique mudanças quando suportado | DMS transfere dados; SCT/conversão suportada ajuda schema/código | Nem toda função/stored procedure é convertida; CDC exige pré-requisitos da origem | Oracle para PostgreSQL: conversão e avaliação mais DMS, não promessa de compatibilidade total.
snow-family | Dispositivos físicos, jobs de transferência e ferramentas locais | Elegibilidade/disponibilidade, volume e procedimento de transferência | Fluxo histórico copiava dados localmente para dispositivo e importava na AWS | Resolve transferência física quando oferta está disponível | Não listado não significa exclusão formal; não recomende contratação ignorando restrições atuais | Pouca banda e muitos dados: avalie transferência física disponível; para novos clientes consulte alternativas atuais da ficha.
datasync-e-transfer-family | Locations/tasks DataSync e endpoints/users Transfer Family | Fonte/destino/protocolo, rede e permissões | DataSync transfere conjuntos de arquivos; Transfer oferece interface de transferência suportada | Atendem movimentação de dados com objetivos diferentes | DataSync não aparece na lista; Transfer Family está fora do escopo; nenhum migra toda lógica da aplicação | Copiar arquivos periodicamente difere de dar endpoint SFTP a parceiros.
cost-explorer | Relatórios, filtros, dimensões, grupos e previsões | Período, granularidade e visão autorizada | Consulte custos processados e compare distribuição/tendências | Ajuda a explicar onde e como se gasta | Não é medidor instantâneo nem bloqueio de consumo; previsão não garante valor final | Descobrir serviço responsável pelo aumento: agrupar por serviço e investigar conta/região/tags.
budgets | Orçamento, thresholds, notificações e actions opcionais | Valor/meta, período, destinatários e permissões de ação | Compara consumo/previsão com meta e notifica ou aplica ação configurada | Ajuda acompanhamento e resposta a custos/uso | Não garante teto rígido da conta: atualização e ações têm latência e alcance limitado | Alertar em 80% do orçamento: Budgets; desligar qualquer recurso não é comportamento automático universal.
pricing-calculator-cur-e-outras-ferramentas | Estimativas, exports detalhados, tags de custo e detecção de anomalia | Premissas, dados exportados, destino e acesso | Estime antes; após uso, analise registros e desvios | Calculator projeta; CUR/Data Exports detalha consumo | Estimativa não é fatura garantida; tag precisa ativação como tag de custo quando aplicável | Planejar nova aplicação: Calculator; auditoria detalhada do gasto real: exportação de custos.
planos-de-suporte | Plano, Support Center, casos, severidade, canais e orientação | Plano aplicável, impacto real e informações do caso | Abra caso elegível; suporte dá resposta inicial e acompanha investigação | Oferece assistência conforme cobertura e termos | Primeira resposta não é resolução; guia da prova e página comercial citam modelos diferentes | Aprenda ambos: Business clássico não se confunde com Business Support+; escolha pelo nome/contexto do enunciado.
recursos-de-ajuda-e-parceiros | Documentação, comunidade, parceiros, Marketplace e serviços profissionais | Necessidade de aprender, comprar, implementar ou reportar incidente | Procure recurso cujo papel corresponde à necessidade | Parceiros integram; Marketplace vende ofertas; suporte atende casos elegíveis | Comprar oferta não transfere toda operação para AWS; re:Post não garante prazo de resposta | Projeto de migração: parceiros/Professional Services; denúncia de abuso: Trust and Safety.
midia-e-jogos | Serviços de mídia/transmissão e infraestrutura especializada de jogos | Tipo de mídia ou servidor de jogo e disponibilidade atual | Consulte a oferta específica quando houver requisito real de produção | Famílias têm funções distintas de conversão, distribuição ou hospedagem | Estão fora do escopo; não memorize configurações como prioridade da CLF-C02 | Vídeo ao vivo não é sinônimo de site estático; conheça a diferença, mas estude primeiro serviços incluídos.
iot-robotica-e-satelite | Ferramentas especializadas de dispositivos, sensores, robótica e satélite | Produto, requisitos físicos e situação de disponibilidade | Avalie documentação e elegibilidade antes de qualquer adoção | Atendem domínios específicos, diferentes de compute genérico | Estão fora do escopo; alguns serviços têm restrições/encerramento indicados na ficha | IoT Core conecta dispositivos no escopo; serviços desta família são contexto adicional.
desenvolvimento-e-aplicacoes | Ferramentas extras de configuração, modelagem, código e aplicações | Oferta atual e problema específico | Avalie a função individual, sem substituir a esteira básica | Diferenciam tarefas como configuração dinâmica e modelagem de recursos | Fora do escopo não implica produto recomendável atualmente; confira encerramentos | Para CLF-C02, diferencie CodeBuild/CodePipeline/X-Ray antes de aprofundar ferramentas extras.
rede-e-diretorio | Descoberta de serviços, conectividade de aplicações e diretórios especializados | Escopo de rede, identidade e serviço | Use a ferramenta compatível com a necessidade específica | Complementam redes e serviços de diretório | Fora do escopo; não são substitutos universais de VPC, DNS ou IAM | DNS Route 53 e identidade IAM são conceitos centrais; ferramentas especializadas pedem contexto próprio.
gerenciamento-e-custos | Ferramentas extras de lifecycle, chat, implantação e custos | Recurso suportado e disponibilidade do produto | Identifique se a necessidade é operar, implantar, comunicar ou contabilizar | Produtos resolvem problemas distintos de governança | Fora do escopo; nomes antigos/renomeados não indicam capacidades novas automaticamente | Para orçamento de conta, estude Budgets; ferramenta extra de custo não substitui a escolha pelo requisito.
""", 7)

def bloco_topico(sec):
    funcionamento, decisao, limite, cenario, resposta = TOPICOS[sec]
    return '\n'.join([
        '<!-- aprofundamento:inicio -->',
        '## 🔬 Aprofundamento para a prova — sem abrir o console', '',
        '**Como funciona:** ' + funcionamento, '',
        '**Como escolher:** ' + decisao, '',
        '**O que não concluir:** ' + limite, '',
        '### Exercício de decisão', '', cenario, '',
        '<details>', '<summary>Resposta e por que as alternativas confundem</summary>', '',
        resposta, '', '</details>', '',
        '**Verifique seu entendimento:** explique a escolha em voz alta e cite uma condição '
        'que mudaria a resposta. Nomear um serviço sem explicar o motivo ainda não demonstra domínio.', '',
        '> Escopo e limites de estudo: [como estudar sem console](../00-guia-do-exame/estudar-sem-console.md). '
        'Os cenários são autorais; não são questões oficiais nem previsão do que cairá.',
        '<!-- aprofundamento:fim -->',
    ])

def bloco_ficha(nome):
    recursos, escolhas, fluxo, capacidade, limite, caso = FICHAS[nome]
    return '\n'.join([
        '<!-- aprofundamento:inicio -->',
        '## 🔬 Ficha prática — visualize o serviço sem console', '',
        '> Este é um mapa dos recursos e decisões, não uma reprodução da tela. '
        'Capacidades dependem da modalidade, região e permissões; '
        'siga o status de escopo no topo desta ficha.', '',
        '| Pergunta | O que você precisa compreender |', '|---|---|',
        '| **O que existe nesse serviço?** | ' + recursos + ' |',
        '| **O que você decide/configura?** | ' + escolhas + ' |',
        '| **Em que ordem as coisas acontecem?** | ' + fluxo + ' |',
        '| **O que pode fazer, e em que condição?** | ' + capacidade + ' |',
        '| **O que não pode presumir?** | ' + limite + ' |', '',
        '**Caso comentado:** ' + caso, '',
        '**Antes de escolher na prova:** identifique o recurso, a ação e o requisito. '
        'Diferencie impossibilidade do serviço de falta de configuração, permissão ou modalidade compatível.', '',
        '**Base técnica:** consulte os links da seção Documentação oficial desta ficha; '
        'as comparações reaproveitam os fundamentos descritos acima. '
        '[Roteiro de leitura](../../docs/00-guia-do-exame/estudar-sem-console.md).',
        '<!-- aprofundamento:fim -->', '',
    ])
