"""Banco de questões no formato da CLF-C02 (dados usados por scripts/gerar_simulado.py).

Cada questão é um dicionário com:
  dominio     "1" a "4"
  secao       tópico do guia (ex.: "2.3"), usado para linkar a explicação
  enunciado   texto da pergunta
  corretas    lista com 1 alternativa (múltipla escolha) ou 2+ (múltipla resposta)
  erradas     distratores (total de alternativas: 4 em múltipla escolha, 5 em múltipla resposta)
  explicacao  por que a resposta está certa e por que os distratores estão errados

As alternativas são embaralhadas de forma determinística pelo gerador; por isso a explicação
cita as alternativas pelo conteúdo, nunca pela letra.
"""

QUESTOES = [
    # ------------------------------------------------------------------ Domínio 1 (16)
    dict(dominio="1", secao="1.2",
         enunciado="Uma varejista comprava servidores extras todo ano para aguentar a Black Friday, e eles ficavam ociosos no resto do tempo. Ao migrar para a AWS, a empresa passou a provisionar capacidade conforme a demanda real. Qual vantagem da computação em nuvem descreve esse ganho?",
         corretas=["Parar de adivinhar a capacidade"],
         erradas=["Beneficiar-se de economias de escala massivas", "Tornar-se global em minutos",
                  "Trocar despesa variável por despesa de capital"],
         explicacao="Dimensionar pela demanda real, sem comprar para o pico, é **parar de adivinhar a capacidade**. Economias de escala tratam de preços menores pelo volume da AWS; ficar global trata de várias regiões; e a troca correta é de despesa de **capital** por despesa **variável** (a alternativa inverte a ordem)."),
    dict(dominio="1", secao="1.2",
         enunciado="Quais DUAS opções são vantagens da computação em nuvem segundo a AWS? (Escolha DUAS.)",
         corretas=["Trocar despesa de capital por despesa variável", "Beneficiar-se de economias de escala massivas"],
         erradas=["Ter acesso físico aos servidores do datacenter da AWS",
                  "Eliminar toda a responsabilidade do cliente pela segurança",
                  "Pagar antecipadamente pelas licenças de todos os serviços"],
         explicacao="As duas fazem parte das 6 vantagens oficiais. Clientes **não** têm acesso físico aos datacenters; a segurança é **compartilhada** (o cliente continua responsável pela segurança *na* nuvem); e o modelo é pagar conforme o uso, não antecipadamente."),
    dict(dominio="1", secao="1.3",
         enunciado="Uma aplicação adiciona instâncias automaticamente quando o tráfego aumenta à noite e as remove de madrugada, quando o tráfego cai. Qual conceito isso demonstra?",
         corretas=["Elasticidade"],
         erradas=["Tolerância a falhas", "Escalabilidade vertical", "Alta disponibilidade"],
         explicacao="**Elasticidade** é crescer **e encolher** automaticamente conforme a carga. Escalabilidade vertical é aumentar o tamanho de uma instância; tolerância a falhas e alta disponibilidade tratam de continuar funcionando quando algo falha, não de acompanhar a demanda."),
    dict(dominio="1", secao="1.3",
         enunciado="Uma empresa aceita perder no máximo 15 minutos de dados em caso de desastre. Esse requisito define qual métrica?",
         corretas=["Recovery Point Objective (RPO)"],
         erradas=["Recovery Time Objective (RTO)", "Acordo de nível de serviço (SLA)", "Tempo médio entre falhas (MTBF)"],
         explicacao="O **RPO** mede a perda máxima aceitável de dados, expressa em tempo. O **RTO** é o tempo máximo para restaurar o serviço; SLA é o compromisso de disponibilidade do provedor; MTBF mede a confiabilidade de um componente."),
    dict(dominio="1", secao="1.3",
         enunciado="Qual estratégia de recuperação de desastres tem o MENOR custo, aceitando o maior tempo de recuperação?",
         corretas=["Backup and Restore"],
         erradas=["Pilot Light", "Warm Standby", "Multi-site active/active"],
         explicacao="Do mais barato e lento ao mais caro e rápido: **Backup and Restore** → Pilot Light → Warm Standby → Multi-site active/active."),
    dict(dominio="1", secao="1.3",
         enunciado="Um time quer que a falha no serviço de processamento de pedidos não derrube o site da loja, e que picos de pedidos sejam absorvidos sem perda. Qual abordagem de arquitetura atende melhor a esse objetivo?",
         corretas=["Desacoplar os componentes com uma fila do Amazon SQS"],
         erradas=["Aumentar o tamanho da instância do site (escala vertical)",
                  "Colocar o site e o processamento na mesma instância EC2",
                  "Usar um único banco de dados para guardar sessões e pedidos"],
         explicacao="**Acoplamento fraco** com uma fila (SQS) faz o site apenas enfileirar pedidos; se o processamento falhar ou ficar lento, as mensagens esperam na fila. As demais opções aumentam o acoplamento ou não resolvem a falha de um componente."),
    dict(dominio="1", secao="1.4",
         enunciado="Uma empresa implanta sua aplicação em várias zonas de disponibilidade e configura recuperação automática de falhas. Qual pilar do AWS Well-Architected Framework ela está aplicando?",
         corretas=["Confiabilidade"],
         erradas=["Excelência operacional", "Eficiência de performance", "Otimização de custos"],
         explicacao="Recuperar-se automaticamente de falhas e usar várias AZs são princípios do pilar **Confiabilidade**. Excelência operacional trata de operar e melhorar processos; eficiência de performance, de usar os recursos certos; otimização de custos, de evitar gastos desnecessários."),
    dict(dominio="1", secao="1.4",
         enunciado="Uma empresa passou a usar instâncias com processadores AWS Graviton e a desligar recursos ociosos com o objetivo de reduzir o impacto ambiental das suas cargas. Qual pilar do Well-Architected Framework orienta essas práticas?",
         corretas=["Sustentabilidade"],
         erradas=["Segurança", "Confiabilidade", "Excelência operacional"],
         explicacao="Reduzir impacto ambiental (maximizar utilização, hardware mais eficiente como Graviton) é o pilar **Sustentabilidade**, o sexto e mais recente pilar. O objetivo declarado na questão é ambiental, não de segurança, resiliência ou operação."),
    dict(dominio="1", secao="1.4",
         enunciado="Um arquiteto quer revisar uma carga de trabalho existente contra as boas práticas dos pilares da AWS e gerar um plano de melhorias, sem custo. Qual serviço ele deve usar?",
         corretas=["AWS Well-Architected Tool"],
         erradas=["AWS Trusted Advisor", "AWS Config", "AWS Security Hub"],
         explicacao="A **Well-Architected Tool** revisa uma carga de trabalho contra os 6 pilares e gera um plano de melhorias. O Trusted Advisor faz verificações automáticas da conta; o Config avalia a configuração de recursos contra regras; o Security Hub centraliza achados de segurança."),
    dict(dominio="1", secao="1.5",
         enunciado="Na adoção de nuvem de uma empresa, um grupo cuida de treinar os funcionários, gerenciar a mudança cultural e redesenhar a estrutura organizacional. Qual perspectiva do AWS Cloud Adoption Framework (CAF) cobre essas atividades?",
         corretas=["People"],
         erradas=["Business", "Governance", "Operations"],
         explicacao="**People** trata de cultura, treinamento, gestão da mudança e desenho organizacional. Business cuida do valor de negócio; Governance, de risco, orçamento e gestão do programa; Operations, de monitoramento e gestão de incidentes."),
    dict(dominio="1", secao="1.5",
         enunciado="Qual é a ordem correta das fases da jornada de transformação na nuvem descritas no AWS CAF?",
         corretas=["Envision, Align, Launch, Scale"],
         erradas=["Align, Envision, Scale, Launch", "Assess, Mobilize, Migrate, Modernize", "Plan, Build, Run, Optimize"],
         explicacao="As quatro fases do CAF são **Envision** (enxergar oportunidades), **Align** (alinhar stakeholders e lacunas), **Launch** (pilotos em produção) e **Scale** (expandir). *Assess, Mobilize, Migrate* são fases de um programa de migração, não do CAF."),
    dict(dominio="1", secao="1.6",
         enunciado="Uma empresa quer migrar seu banco de dados MySQL de um servidor próprio para o Amazon RDS, reduzindo a administração, sem alterar o código da aplicação. Qual estratégia de migração é essa?",
         corretas=["Replatform"],
         erradas=["Rehost", "Refactor", "Repurchase"],
         explicacao="**Replatform** (lift-tinker-and-shift) faz pequenas otimizações, como trocar o banco autogerenciado por um serviço gerenciado, sem reescrever a aplicação. Rehost move sem mudanças; Refactor reescreve para cloud-native; Repurchase troca por outro produto (geralmente SaaS)."),
    dict(dominio="1", secao="1.6",
         enunciado="Uma empresa precisa sair do datacenter em 3 meses e quer mover centenas de VMs para o Amazon EC2 sem nenhuma alteração. Qual estratégia de migração é a mais adequada?",
         corretas=["Rehost"],
         erradas=["Replatform", "Refactor", "Retain"],
         explicacao="**Rehost** (lift-and-shift) é a estratégia mais rápida e move as VMs sem mudanças, normalmente com o AWS Application Migration Service. Retain manteria as aplicações on-premises; Replatform e Refactor exigem alterações."),
    dict(dominio="1", secao="1.1",
         enunciado="Uma empresa precisa manter dados de clientes em seu datacenter por exigência regulatória, mas quer usar a AWS para o restante das aplicações, com as duas partes conectadas. Qual modelo de implantação atende a esse cenário?",
         corretas=["Híbrido"],
         erradas=["Nuvem pública (all-in)", "On-premises (nuvem privada)", "Software como serviço (SaaS)"],
         explicacao="Parte on-premises e parte na nuvem, conectadas (VPN, Direct Connect, Outposts), é o modelo **híbrido**. SaaS é um modelo de *serviço*, não de implantação."),
    dict(dominio="1", secao="1.1",
         enunciado="Um desenvolvedor quer apenas enviar o código da sua aplicação web Java e deixar a AWS cuidar de provisionamento, balanceamento de carga e escalonamento. Qual modelo de serviço e qual serviço AWS atendem a esse cenário?",
         corretas=["PaaS, com o AWS Elastic Beanstalk"],
         erradas=["IaaS, com o Amazon EC2", "SaaS, com o Amazon WorkSpaces", "IaaS, com o Amazon VPC"],
         explicacao="No **PaaS** o cliente entrega o código e a plataforma gerencia o resto; o **Elastic Beanstalk** é o exemplo clássico. EC2 e VPC são IaaS (o cliente gerencia o SO e a rede); WorkSpaces é um desktop virtual pronto."),
    dict(dominio="1", secao="1.7",
         enunciado="A diretoria de uma empresa pede uma estimativa do custo total de propriedade (TCO) de mover todo o ambiente on-premises para a AWS, para montar o caso de negócio da migração. Qual serviço ajuda nisso?",
         corretas=["Migration Evaluator"],
         erradas=["AWS Cost Explorer", "AWS Budgets", "AWS Migration Hub"],
         explicacao="O **Migration Evaluator** analisa o ambiente atual e monta o caso de negócio (TCO) da migração. Cost Explorer e Budgets trabalham com gastos de recursos que já estão na AWS; o Migration Hub acompanha o progresso das migrações."),

    # ------------------------------------------------------------------ Domínio 2 (20)
    dict(dominio="2", secao="2.1",
         enunciado="Segundo o modelo de responsabilidade compartilhada, quem é responsável por aplicar patches no sistema operacional convidado de uma instância Amazon EC2?",
         corretas=["O cliente"],
         erradas=["A AWS", "A AWS e o cliente, em partes iguais", "O fornecedor do sistema operacional"],
         explicacao="No EC2 (IaaS), o **cliente** gerencia o SO convidado, os patches, as aplicações e os security groups. A AWS cuida do hardware, da rede física e do hipervisor."),
    dict(dominio="2", secao="2.1",
         enunciado="Uma empresa usa o Amazon RDS for MySQL. Quem é responsável por aplicar os patches do mecanismo de banco de dados?",
         corretas=["A AWS"],
         erradas=["O cliente", "Um parceiro da AWS Partner Network", "O administrador de banco de dados do cliente, manualmente"],
         explicacao="Em serviços gerenciados como o RDS, a **AWS** aplica os patches do SO e do mecanismo do banco (na janela de manutenção definida pelo cliente). O cliente cuida de usuários do banco, acesso de rede, criptografia e dados."),
    dict(dominio="2", secao="2.1",
         enunciado="Quais DUAS tarefas são de responsabilidade do CLIENTE segundo o modelo de responsabilidade compartilhada? (Escolha DUAS.)",
         corretas=["Configurar os security groups das instâncias", "Ativar a criptografia dos dados armazenados no Amazon S3"],
         erradas=["Garantir a segurança física dos datacenters",
                  "Manter o hipervisor das instâncias EC2",
                  "Destruir os discos físicos ao fim da vida útil"],
         explicacao="Security groups e criptografia dos dados são segurança **na** nuvem (cliente). Segurança física, hipervisor e descarte de discos são segurança **da** nuvem (AWS)."),
    dict(dominio="2", secao="2.2",
         enunciado="Qual destas tarefas só pode ser realizada pelo usuário root da conta AWS?",
         corretas=["Alterar o plano de AWS Support"],
         erradas=["Criar um usuário IAM com permissões de administrador",
                  "Visualizar a fatura mensal",
                  "Lançar uma instância EC2"],
         explicacao="Alterar ou cancelar o **plano de suporte** exige o root, assim como fechar a conta e mudar dados da conta. Criar usuários IAM, ver faturas (com permissão) e lançar instâncias podem ser feitos por identidades IAM."),
    dict(dominio="2", secao="2.3",
         enunciado="Uma aplicação executada em instâncias EC2 precisa ler objetos de um bucket S3. Qual é a forma MAIS segura de conceder esse acesso?",
         corretas=["Anexar uma IAM role com as permissões necessárias às instâncias"],
         erradas=["Guardar access keys de um usuário IAM no código da aplicação",
                  "Tornar o bucket público",
                  "Usar as credenciais do usuário root na aplicação"],
         explicacao="Uma **IAM role** (via instance profile) entrega credenciais **temporárias** e rotacionadas automaticamente. Access keys no código podem vazar; bucket público expõe os dados a todos; o root nunca deve ser usado em aplicações."),
    dict(dominio="2", secao="2.3",
         enunciado="Um usuário IAM recebe uma política que permite (Allow) apagar objetos de um bucket S3 e, por meio de um grupo, outra política que nega explicitamente (Deny) a mesma ação. O que acontece quando ele tenta apagar um objeto?",
         corretas=["A ação é negada, porque um Deny explícito sempre prevalece"],
         erradas=["A ação é permitida, porque a política mais recente prevalece",
                  "A ação é permitida, porque políticas de usuário prevalecem sobre as de grupo",
                  "O IAM retorna erro de política conflitante e bloqueia o usuário"],
         explicacao="Na avaliação de políticas do IAM, tudo começa negado, um Allow libera e um **Deny explícito sempre vence**, independentemente de onde a política esteja anexada ou de quando foi criada."),
    dict(dominio="2", secao="2.3",
         enunciado="Uma empresa com 30 contas AWS quer que os funcionários façam login uma única vez, usando o diretório corporativo, e acessem as contas permitidas para cada um. Qual serviço atende a essa necessidade?",
         corretas=["AWS IAM Identity Center"],
         erradas=["Amazon Cognito", "Usuários IAM criados em cada conta", "AWS Secrets Manager"],
         explicacao="O **IAM Identity Center** oferece login único (SSO) para várias contas do Organizations e aplicações, integrado a diretórios externos. Cognito é para usuários finais de aplicações; criar usuários em cada conta não escala; Secrets Manager guarda segredos."),
    dict(dominio="2", secao="2.3",
         enunciado="Um aplicativo móvel precisa permitir que clientes se cadastrem e façam login com suas contas do Google ou do Facebook. Qual serviço AWS deve ser usado?",
         corretas=["Amazon Cognito"],
         erradas=["AWS IAM Identity Center", "AWS Directory Service", "AWS IAM"],
         explicacao="O **Cognito** (user pools) oferece cadastro, login e login social para **usuários finais** de aplicações web e mobile. Identity Center e Directory Service são para funcionários; usuários IAM não são para clientes de uma aplicação."),
    dict(dominio="2", secao="2.3",
         enunciado="Uma empresa precisa armazenar a senha do banco de dados Amazon RDS de forma criptografada e trocá-la automaticamente a cada 30 dias, sem alterar o código a cada troca. Qual serviço atende MELHOR a esse requisito?",
         corretas=["AWS Secrets Manager"],
         erradas=["AWS Systems Manager Parameter Store", "AWS Key Management Service (AWS KMS)", "Amazon S3 com criptografia SSE-KMS"],
         explicacao="O **Secrets Manager** tem **rotação automática nativa** de credenciais do RDS. O Parameter Store guarda parâmetros e segredos, mas sem rotação nativa; o KMS gerencia chaves de criptografia, não segredos; o S3 não é um cofre de segredos."),
    dict(dominio="2", secao="2.4",
         enunciado="Uma empresa usa o AWS Organizations e quer impedir que qualquer conta da OU de desenvolvimento use a região sa-east-1, inclusive administradores dessas contas. O que deve ser usado?",
         corretas=["Uma Service Control Policy (SCP) aplicada à OU"],
         erradas=["Uma política IAM anexada a cada usuário administrador",
                  "Uma regra do AWS Config em cada conta",
                  "Uma bucket policy do S3"],
         explicacao="A **SCP** define o limite máximo de permissões de todas as contas de uma OU e vale até para administradores. Políticas IAM podem ser alteradas pelos próprios administradores; o Config detecta, mas não impede; bucket policy só controla um bucket."),
    dict(dominio="2", secao="2.5",
         enunciado="Uma instituição financeira precisa, por regulação, de módulos de segurança de hardware (HSM) dedicados exclusivamente a ela, validados FIPS 140 nível 3, com controle exclusivo das chaves. Qual serviço atende a esse requisito?",
         corretas=["AWS CloudHSM"],
         erradas=["AWS Key Management Service (AWS KMS) com chaves gerenciadas pela AWS",
                  "AWS Certificate Manager (ACM)",
                  "AWS Secrets Manager"],
         explicacao="O **CloudHSM** oferece HSM **single-tenant**, com chaves sob controle exclusivo do cliente. O KMS usa HSMs compartilhados gerenciados pela AWS; o ACM gerencia certificados TLS; o Secrets Manager guarda segredos."),
    dict(dominio="2", secao="2.6",
         enunciado="O auditor de uma empresa pediu o relatório SOC 2 da AWS para avaliar os controles do provedor. Onde a empresa obtém esse documento?",
         corretas=["AWS Artifact"],
         erradas=["AWS Audit Manager", "AWS Config", "AWS Trusted Advisor"],
         explicacao="O **AWS Artifact** é o portal de autoatendimento para baixar relatórios de conformidade **da AWS** (SOC, PCI, ISO) e aceitar acordos como o BAA. O Audit Manager coleta evidências **da conta do cliente** para a auditoria dele."),
    dict(dominio="2", secao="2.7",
         enunciado="Uma instância EC2 de produção foi encerrada e o time precisa descobrir qual usuário fez isso, quando e de qual endereço IP. Qual serviço fornece essa informação?",
         corretas=["AWS CloudTrail"],
         erradas=["Amazon CloudWatch", "AWS Config", "VPC Flow Logs"],
         explicacao="O **CloudTrail** registra as chamadas de API (quem, o quê, quando, de onde). O CloudWatch monitora métricas e logs de desempenho; o Config registra o estado da configuração; os Flow Logs registram tráfego de rede, não ações de API."),
    dict(dominio="2", secao="2.7",
         enunciado="O time de segurança precisa saber como estavam configuradas as regras de um security group na semana passada e ser alertado sempre que algum security group permitir SSH a partir de qualquer IP. Qual serviço atende a esses requisitos?",
         corretas=["AWS Config"],
         erradas=["AWS CloudTrail", "Amazon Inspector", "Amazon Macie"],
         explicacao="O **AWS Config** guarda o histórico de configuração dos recursos e avalia continuamente a conformidade com regras (ex.: `restricted-ssh`). O CloudTrail mostra quem fez a mudança, mas não avalia regras; Inspector busca vulnerabilidades; Macie busca dados sensíveis no S3."),
    dict(dominio="2", secao="2.8",
         enunciado="Quais DUAS afirmações sobre security groups e network ACLs estão corretas? (Escolha DUAS.)",
         corretas=["Security groups são stateful: o tráfego de retorno é liberado automaticamente",
                   "Network ACLs atuam no nível da subnet e aceitam regras de permissão e de negação"],
         erradas=["Security groups aceitam regras de negação para bloquear um IP específico",
                  "Network ACLs são stateful e atuam no nível da instância",
                  "Security groups são aplicados a subnets inteiras"],
         explicacao="Security groups atuam na instância/ENI, são **stateful** e só têm regras de permissão. Network ACLs atuam na **subnet**, são **stateless** e aceitam **permitir e negar** — por isso são usadas para bloquear um IP específico."),
    dict(dominio="2", secao="2.8",
         enunciado="Uma loja virtual atrás de um Application Load Balancer está sofrendo tentativas de SQL injection e cross-site scripting (XSS). Qual serviço deve ser usado para bloquear essas requisições?",
         corretas=["AWS WAF"],
         erradas=["AWS Shield Standard", "Security groups", "Amazon GuardDuty"],
         explicacao="O **WAF** é um firewall de camada 7 que filtra requisições web (SQL injection, XSS, rate limiting) e se associa ao ALB. O Shield protege contra DDoS; security groups filtram por IP/porta; o GuardDuty detecta ameaças, mas não bloqueia requisições."),
    dict(dominio="2", secao="2.8",
         enunciado="Uma empresa de jogos quer proteção ampliada contra DDoS, acesso 24/7 a uma equipe especializada durante ataques e créditos pelos custos de escalonamento causados por ataques. Qual serviço atende a esses requisitos?",
         corretas=["AWS Shield Advanced"],
         erradas=["AWS Shield Standard", "AWS WAF", "AWS Firewall Manager"],
         explicacao="O **Shield Advanced** inclui o Shield Response Team (SRT) 24/7 e **proteção de custo**. O Shield Standard é gratuito e automático, mas não tem esses extras; o WAF filtra requisições web; o Firewall Manager gerencia regras centralmente."),
    dict(dominio="2", secao="2.9",
         enunciado="Uma empresa quer detectar automaticamente atividades maliciosas, como uma instância EC2 minerando criptomoedas ou se comunicando com IPs conhecidos de ataque, analisando CloudTrail, VPC Flow Logs e logs de DNS. Qual serviço atende a esse requisito?",
         corretas=["Amazon GuardDuty"],
         erradas=["Amazon Inspector", "Amazon Macie", "AWS Artifact"],
         explicacao="O **GuardDuty** detecta ameaças ativas com ML e inteligência de ameaças a partir desses logs, sem agentes. O Inspector busca vulnerabilidades de software; o Macie, dados sensíveis no S3; o Artifact fornece relatórios de conformidade."),
    dict(dominio="2", secao="2.9",
         enunciado="O time de segurança precisa descobrir quais buckets S3 contêm dados pessoais, como números de cartão de crédito e documentos de identidade. Qual serviço deve ser usado?",
         corretas=["Amazon Macie"],
         erradas=["Amazon Inspector", "Amazon Detective", "AWS Shield"],
         explicacao="O **Macie** usa ML e padrões para descobrir dados sensíveis (PII) no **S3**. O Inspector busca CVEs em EC2, ECR e Lambda; o Detective investiga a causa raiz de achados; o Shield protege contra DDoS."),
    dict(dominio="2", secao="2.9",
         enunciado="Uma empresa quer varrer continuamente suas instâncias EC2 e as imagens de contêiner no Amazon ECR em busca de vulnerabilidades de software conhecidas (CVEs). Qual serviço deve ser usado?",
         corretas=["Amazon Inspector"],
         erradas=["Amazon GuardDuty", "AWS Trusted Advisor", "AWS Config"],
         explicacao="O **Inspector** avalia vulnerabilidades de software e exposição de rede em EC2, ECR e Lambda. O GuardDuty detecta ameaças em andamento; o Trusted Advisor dá recomendações de boas práticas; o Config avalia configurações, não CVEs."),

    # ------------------------------------------------------------------ Domínio 3 (21)
    dict(dominio="3", secao="3.2",
         enunciado="Quais DOIS fatores uma empresa deve considerar ao escolher a região AWS para uma nova aplicação? (Escolha DUAS.)",
         corretas=["Requisitos de conformidade e residência de dados", "Proximidade dos clientes para reduzir a latência"],
         erradas=["A quantidade de usuários IAM da conta",
                  "A data de criação da conta AWS",
                  "O número de buckets S3 já existentes"],
         explicacao="Os quatro fatores clássicos são **conformidade/residência de dados**, **latência para os clientes**, **serviços disponíveis na região** e **preço**. Usuários IAM, idade da conta e buckets existentes não influenciam a escolha."),
    dict(dominio="3", secao="3.2",
         enunciado="Um hospital precisa processar dados localmente, no próprio datacenter, por exigência de residência de dados, mas quer usar as mesmas APIs, ferramentas e serviços da AWS. Qual solução atende a esse requisito?",
         corretas=["AWS Outposts"],
         erradas=["AWS Local Zones", "AWS Wavelength", "Amazon CloudFront"],
         explicacao="O **Outposts** instala racks ou servidores da AWS **no datacenter do cliente**. Local Zones ficam em cidades e são operadas pela AWS; Wavelength fica dentro de redes 5G de operadoras; CloudFront é uma CDN."),
    dict(dominio="3", secao="3.3",
         enunciado="Uma empresa vai executar um banco de dados em memória de alto desempenho no Amazon EC2. Qual família de instâncias é a mais indicada?",
         corretas=["Otimizada para memória (por exemplo, R ou X)"],
         erradas=["Otimizada para computação (por exemplo, C)",
                  "Uso geral com desempenho expansível (por exemplo, T)",
                  "Computação acelerada (por exemplo, P ou G)"],
         explicacao="Bancos em memória e análises em tempo real usam instâncias **otimizadas para memória** (R, X). C é para uso intenso de CPU; T é para cargas leves com picos; P e G são para GPU/ML."),
    dict(dominio="3", secao="3.3",
         enunciado="Uma aplicação grava arquivos temporários de cache no instance store de uma instância EC2. O que acontece com esses dados quando a instância é PARADA (stop)?",
         corretas=["Os dados são perdidos"],
         erradas=["Os dados são copiados automaticamente para um snapshot do EBS",
                  "Os dados são preservados e ficam disponíveis quando a instância voltar",
                  "Os dados são movidos automaticamente para o Amazon S3"],
         explicacao="O **instance store** é armazenamento local **efêmero**: os dados se perdem ao parar, hibernar ou encerrar a instância (sobrevivem só ao reboot). Para persistência, use EBS."),
    dict(dominio="3", secao="3.4",
         enunciado="Uma aplicação de microsserviços precisa enviar requisições com caminho /api para um grupo de contêineres e /imagens para outro, usando o mesmo endereço. Qual load balancer deve ser usado?",
         corretas=["Application Load Balancer"],
         erradas=["Network Load Balancer", "Gateway Load Balancer", "Classic Load Balancer"],
         explicacao="O **ALB** opera na camada 7 e roteia por caminho, host e cabeçalho. O NLB opera na camada 4 (TCP/UDP); o GWLB encaminha tráfego para appliances de segurança; o Classic é legado e não recomendado."),
    dict(dominio="3", secao="3.5",
         enunciado="Um processamento de vídeo leva cerca de 2 horas por arquivo. A empresa quer executá-lo em contêineres, sem provisionar nem gerenciar servidores. Qual opção é a mais adequada?",
         corretas=["Amazon ECS com AWS Fargate"],
         erradas=["AWS Lambda", "Amazon EC2 com Auto Scaling", "Amazon Lightsail"],
         explicacao="O **Fargate** executa contêineres sem servidores e sem limite de duração. O Lambda tem limite de **15 minutos** por execução; EC2 e Lightsail exigem gerenciar servidores."),
    dict(dominio="3", secao="3.5",
         enunciado="Uma empresa já usa Kubernetes on-premises e quer migrar seus manifestos e ferramentas para um serviço gerenciado na AWS, com o plano de controle operado pela AWS. Qual serviço atende melhor?",
         corretas=["Amazon EKS"],
         erradas=["Amazon ECS", "AWS Elastic Beanstalk", "AWS Batch"],
         explicacao="O **EKS** é Kubernetes gerenciado e preserva manifestos e ferramentas do ecossistema. O ECS é o orquestrador próprio da AWS (não Kubernetes); Beanstalk é PaaS para aplicações; Batch é para jobs em lote."),
    dict(dominio="3", secao="3.7",
         enunciado="Um jogo online precisa armazenar o perfil e o progresso de milhões de jogadores com latência de milissegundos de um dígito, em qualquer escala, sem gerenciar servidores. Qual banco de dados atende melhor?",
         corretas=["Amazon DynamoDB"],
         erradas=["Amazon RDS for PostgreSQL", "Amazon Redshift", "Amazon Neptune"],
         explicacao="O **DynamoDB** é NoSQL chave-valor serverless, com latência de milissegundos de um dígito em qualquer escala. RDS é relacional e exige dimensionar instâncias; Redshift é data warehouse (OLAP); Neptune é banco de grafos."),
    dict(dominio="3", secao="3.7",
         enunciado="Uma empresa quer que seu banco Amazon RDS continue disponível mesmo se uma zona de disponibilidade inteira falhar, com failover automático. Qual recurso deve ser habilitado?",
         corretas=["RDS Multi-AZ"],
         erradas=["Read replicas na mesma região", "Snapshots manuais diários", "Amazon ElastiCache na frente do banco"],
         explicacao="O **Multi-AZ** mantém um standby síncrono em outra AZ com **failover automático** — o objetivo é disponibilidade. Read replicas escalam leitura; snapshots exigem restauração manual; ElastiCache é cache, não alta disponibilidade do banco."),
    dict(dominio="3", secao="3.7",
         enunciado="O time de BI precisa executar consultas SQL analíticas complexas sobre petabytes de dados históricos de vendas, alimentando dashboards. Qual serviço é o mais indicado?",
         corretas=["Amazon Redshift"],
         erradas=["Amazon RDS for MySQL", "Amazon DynamoDB", "Amazon ElastiCache"],
         explicacao="O **Redshift** é o data warehouse colunar para análises (OLAP) em grande escala. RDS é otimizado para transações (OLTP); DynamoDB é NoSQL chave-valor; ElastiCache é cache em memória."),
    dict(dominio="3", secao="3.8",
         enunciado="Uma empresa armazena milhões de objetos no Amazon S3 com padrão de acesso imprevisível: alguns são lidos com frequência e outros ficam meses sem acesso. Qual classe de armazenamento otimiza o custo automaticamente sem afetar o desempenho?",
         corretas=["S3 Intelligent-Tiering"],
         erradas=["S3 Standard", "S3 One Zone-IA", "S3 Glacier Deep Archive"],
         explicacao="O **Intelligent-Tiering** move os objetos entre camadas automaticamente conforme o acesso, sem taxa de recuperação. Standard não otimiza custo; One Zone-IA cobra recuperação e guarda em uma AZ; Deep Archive tem recuperação de horas."),
    dict(dominio="3", secao="3.8",
         enunciado="Por exigência regulatória, uma empresa precisa guardar registros por 7 anos. Eles quase nunca são lidos e uma recuperação de até 48 horas é aceitável. Qual é a opção de MENOR custo?",
         corretas=["S3 Glacier Deep Archive"],
         erradas=["S3 Glacier Instant Retrieval", "S3 Standard-IA", "S3 Intelligent-Tiering"],
         explicacao="O **Glacier Deep Archive** é a classe mais barata, para retenção de longo prazo, com recuperação em até 12 h (padrão) ou 48 h (bulk). Instant Retrieval e Standard-IA custam mais por oferecerem acesso em milissegundos."),
    dict(dominio="3", secao="3.9",
         enunciado="Dezenas de instâncias Linux distribuídas em várias zonas de disponibilidade precisam ler e gravar os mesmos arquivos ao mesmo tempo. Qual serviço de armazenamento atende a esse requisito?",
         corretas=["Amazon EFS"],
         erradas=["Amazon EBS", "Instance store", "Amazon FSx for Windows File Server"],
         explicacao="O **EFS** é um sistema de arquivos NFS compartilhado entre muitas instâncias Linux em várias AZs. O EBS fica preso a uma AZ (Multi-Attach só io1/io2, mesma AZ); instance store é local e efêmero; FSx for Windows é SMB para Windows."),
    dict(dominio="3", secao="3.9",
         enunciado="Uma empresa quer acabar com o backup em fitas físicas, mas sem trocar o software de backup que já usa. Qual solução atende a esse requisito?",
         corretas=["AWS Storage Gateway com Tape Gateway"],
         erradas=["AWS DataSync", "Amazon EFS", "AWS Snowball Edge"],
         explicacao="O **Tape Gateway** apresenta fitas virtuais (VTL) ao software de backup e arquiva os dados no S3 Glacier. DataSync transfere arquivos; EFS é sistema de arquivos; Snowball Edge é transferência física pontual."),
    dict(dominio="3", secao="3.10",
         enunciado="Instâncias EC2 em uma subnet privada precisam baixar atualizações de segurança da internet, mas não podem receber conexões iniciadas de fora. O que deve ser configurado?",
         corretas=["Um NAT Gateway em uma subnet pública, com rota a partir da subnet privada"],
         erradas=["Um Internet Gateway com rota direta a partir da subnet privada",
                  "Um gateway VPC endpoint para o Amazon S3",
                  "Um VPC peering com a VPC padrão"],
         explicacao="O **NAT Gateway** permite apenas a **saída** para a internet a partir de subnets privadas. Uma rota direta para o Internet Gateway tornaria a subnet pública; o gateway endpoint só acessa S3/DynamoDB; peering liga VPCs, não dá acesso à internet."),
    dict(dominio="3", secao="3.10",
         enunciado="Uma empresa transfere grandes volumes de dados todos os dias entre o datacenter e a AWS e precisa de uma conexão privada, dedicada, que não passe pela internet e tenha desempenho consistente. Qual serviço atende a esse requisito?",
         corretas=["AWS Direct Connect"],
         erradas=["AWS Site-to-Site VPN", "AWS Client VPN", "Amazon CloudFront"],
         explicacao="O **Direct Connect** é um link físico dedicado e privado, com banda estável. A Site-to-Site VPN passa pela internet (criptografada); a Client VPN é para usuários remotos; CloudFront é CDN."),
    dict(dominio="3", secao="3.10",
         enunciado="Uma empresa de mídia quer reduzir a latência na entrega de vídeos e imagens para usuários no mundo todo, fazendo cache do conteúdo perto deles. Qual serviço deve ser usado?",
         corretas=["Amazon CloudFront"],
         erradas=["AWS Global Accelerator", "Amazon Route 53", "AWS Direct Connect"],
         explicacao="O **CloudFront** é a CDN da AWS e faz **cache** nas edge locations. O Global Accelerator otimiza o caminho de rede TCP/UDP, mas **não faz cache**; o Route 53 é DNS; o Direct Connect liga datacenters à AWS."),
    dict(dominio="3", secao="3.13",
         enunciado="Quando um pedido é criado, a mesma mensagem precisa ser entregue a três sistemas diferentes e também enviada por e-mail ao time financeiro. Qual serviço deve receber a publicação do evento?",
         corretas=["Amazon SNS"],
         erradas=["Amazon SQS", "AWS Step Functions", "Amazon Kinesis Data Streams"],
         explicacao="O **SNS** é pub/sub: publica num tópico e empurra a mensagem para vários assinantes (filas SQS, Lambda, HTTP, e-mail). Uma fila SQS é consumida por um processador; Step Functions orquestra etapas; Kinesis é para streaming em tempo real."),
    dict(dominio="3", secao="3.11",
         enunciado="Um analista quer consultar com SQL padrão os logs armazenados em um bucket S3, sem provisionar servidores e pagando apenas pelos dados lidos em cada consulta. Qual serviço atende a esse requisito?",
         corretas=["Amazon Athena"],
         erradas=["Amazon Redshift", "Amazon EMR", "Amazon RDS"],
         explicacao="O **Athena** executa SQL serverless direto no S3 e cobra por dados escaneados. Redshift exige carregar dados num data warehouse; EMR exige clusters de big data; RDS é banco transacional."),
    dict(dominio="3", secao="3.12",
         enunciado="Uma seguradora recebe milhares de formulários escaneados e quer extrair automaticamente o texto, os campos (chave-valor) e as tabelas. Qual serviço deve ser usado?",
         corretas=["Amazon Textract"],
         erradas=["Amazon Rekognition", "Amazon Comprehend", "Amazon Transcribe"],
         explicacao="O **Textract** extrai texto, formulários e tabelas de documentos digitalizados. O Rekognition analisa imagens e vídeos (rostos, objetos); o Comprehend analisa texto já extraído (sentimento, entidades); o Transcribe converte fala em texto."),
    dict(dominio="3", secao="3.17",
         enunciado="Uma empresa quer migrar um banco Oracle on-premises para o Amazon Aurora PostgreSQL, mantendo o banco de origem em operação durante a migração. Quais serviços devem ser usados?",
         corretas=["AWS Schema Conversion Tool (SCT) e AWS Database Migration Service (DMS)"],
         erradas=["Somente o AWS Application Migration Service",
                  "AWS DataSync e AWS Transfer Family",
                  "AWS Snowball Edge e Amazon S3"],
         explicacao="Migração **heterogênea**: o **SCT** converte o schema e o código do Oracle para PostgreSQL, e o **DMS** move os dados com replicação contínua (CDC). O Application Migration Service migra servidores inteiros; DataSync, Transfer Family e Snowball transferem arquivos."),

    # ------------------------------------------------------------------ Domínio 4 (8)
    dict(dominio="4", secao="4.2",
         enunciado="Uma empresa executa renderizações de vídeo em lote que podem ser interrompidas e retomadas depois, sem prazo rígido. Qual opção de compra do EC2 oferece o MENOR custo?",
         corretas=["Spot Instances"],
         erradas=["On-Demand Instances", "Dedicated Hosts", "Reserved Instances Standard de 3 anos"],
         explicacao="As **Spot Instances** oferecem até 90% de desconto para cargas tolerantes a interrupção (aviso de 2 minutos). On-Demand é mais caro; Dedicated Hosts são os mais caros; RIs exigem compromisso de 1 ou 3 anos e fazem sentido para cargas estáveis."),
    dict(dominio="4", secao="4.2",
         enunciado="Uma empresa usa Amazon EC2 em várias regiões, AWS Fargate e AWS Lambda, e quer um desconto com compromisso de 1 ano que se aplique automaticamente a todos esses serviços, mesmo se mudar a família de instâncias. Qual opção atende a esse requisito?",
         corretas=["Compute Savings Plans"],
         erradas=["EC2 Instance Savings Plans", "Reserved Instances Standard", "Spot Instances"],
         explicacao="O **Compute Savings Plans** vale para EC2 de qualquer família e região, Fargate e Lambda. O EC2 Instance Savings Plans fica preso a uma família numa região; RIs Standard ficam presas a um tipo de instância; Spot não tem compromisso nem cobre Lambda."),
    dict(dominio="4", secao="4.4",
         enunciado="Antes de migrar, uma empresa quer estimar o custo mensal de uma nova arquitetura com EC2, RDS e S3, e compartilhar a estimativa com a diretoria. Qual ferramenta deve ser usada?",
         corretas=["AWS Pricing Calculator"],
         erradas=["AWS Cost Explorer", "AWS Budgets", "AWS Cost and Usage Report"],
         explicacao="A **Pricing Calculator** estima custos **antes** de criar recursos e gera estimativas compartilháveis. Cost Explorer, Budgets e CUR trabalham com gastos **reais** de recursos já em uso."),
    dict(dominio="4", secao="4.4",
         enunciado="O gerente financeiro quer ser notificado por e-mail quando o gasto PREVISTO do mês ultrapassar US$ 5.000. Qual serviço deve ser configurado?",
         corretas=["AWS Budgets"],
         erradas=["AWS Cost Explorer", "AWS Pricing Calculator", "AWS Trusted Advisor"],
         explicacao="O **Budgets** dispara alertas quando o gasto real **ou previsto** passa de um limite (e pode até executar ações). O Cost Explorer analisa e prevê, mas não alerta por limite; a Pricing Calculator estima antes de usar; o Trusted Advisor dá recomendações."),
    dict(dominio="4", secao="4.4",
         enunciado="Uma empresa com uma única conta AWS precisa saber quanto cada departamento gasta para fazer o rateio interno dos custos. Qual é a forma recomendada?",
         corretas=["Aplicar cost allocation tags aos recursos e ativá-las no console de Billing"],
         erradas=["Criar um usuário IAM para cada departamento",
                  "Usar o AWS Pricing Calculator mensalmente",
                  "Abrir um caso no AWS Support pedindo o relatório"],
         explicacao="As **cost allocation tags** (ex.: `departamento=marketing`), depois de **ativadas** no Billing, separam os custos no Cost Explorer e no CUR. Usuários IAM não separam custos de recursos; a calculadora estima custos futuros; o suporte não faz rateio."),
    dict(dominio="4", secao="4.5",
         enunciado="Uma startup quer o plano de AWS Support pago de MENOR custo, que começa em US$ 29 por mês por conta e oferece resposta em até 30 minutos para casos críticos. Qual plano atende a esse requisito?",
         corretas=["AWS Business Support+"],
         erradas=["Basic", "AWS Enterprise Support", "AWS Unified Operations"],
         explicacao="O **Business Support+** é o plano pago de entrada do modelo atual (task 4.3 do exam guide): a partir de US$ 29/mês por conta, com resposta de 30 minutos para casos críticos. O Basic é gratuito e não tem suporte técnico; o Enterprise começa em US$ 5.000/mês (15 min); o Unified Operations, em US$ 50.000/mês (5 min)."),
    dict(dominio="4", secao="4.5",
         enunciado="Uma grande empresa precisa de um Technical Account Manager (TAM) designado e de resposta em até 15 minutos quando um sistema crítico estiver fora do ar, pelo MENOR custo. Qual plano de suporte atende a esses requisitos?",
         corretas=["AWS Enterprise Support"],
         erradas=["AWS Business Support+", "Basic", "AWS Unified Operations"],
         explicacao="O **Enterprise Support** inclui TAM **designado** e resposta em 15 minutos para casos críticos, a partir de US$ 5.000/mês — atende ao requisito com o menor custo. O Business Support+ responde em 30 minutos e não tem TAM designado; o Basic não tem suporte técnico; o Unified Operations (5 min) também atenderia, mas custa a partir de US$ 50.000/mês."),
    dict(dominio="4", secao="4.3",
         enunciado="Quais DOIS tipos de transferência de dados são GRATUITOS na AWS? (Escolha DUAS.)",
         corretas=["Entrada de dados da internet para a AWS",
                   "Transferência de uma origem na AWS (como o S3) para o Amazon CloudFront"],
         erradas=["Saída de dados da AWS para a internet",
                  "Transferência entre regiões AWS",
                  "Transferência entre zonas de disponibilidade da mesma região"],
         explicacao="A **entrada** de dados da internet e a transferência de **origens AWS para o CloudFront** são gratuitas. A saída para a internet, a transferência entre regiões e a transferência entre AZs são cobradas."),
]
