"""Casos resolvidos autorais para ligar recursos, decisões e consequência."""
CASOS = {}
_DADOS = """
ec2 | A escola já tem um programa de matrícula que precisa de Linux e de instalação própria. O objetivo não é guardar somente arquivos: é executar esse programa e atender os alunos. A equipe escolhe EC2 porque precisa administrar esse ambiente. | Ela escolhe uma AMI compatível, isto é, uma base com o sistema; depois um tipo de instância com capacidade adequada. Um volume EBS fornece disco. A conexão de rede permite o caminho dos visitantes; o security group limita tráfego permitido. A aplicação ainda precisa ser instalada e configurada para responder. Se ela chamar serviços AWS, uma role pode fornecer permissões temporárias. | Ao encerrar o estudo, parar a máquina interrompe sua execução nas condições aplicáveis, mas não apaga necessariamente volumes e cópias. Por isso, confira cada recurso conservado. S3 resolveria guardar PDFs, mas não executaria esse programa Linux. Lambda seria outra forma de execução, com modelo e limites diferentes; não é uma troca direta para qualquer servidor.
s3 | A escola quer disponibilizar apostilas em PDF sem manter cada documento num disco específico de seu servidor. O trabalho principal é conservar e obter arquivos, não executar o sistema de matrícula. | Ela cria um bucket e envia um PDF como objeto, com uma chave como materiais/aula-1.pdf. A chave identifica o conteúdo; o nome não cria uma pasta de sistema operacional. O aplicativo solicita o objeto com autorização adequada. Não é preciso liberar o bucket inteiro ao público para que um fluxo autorizado obtenha o arquivo. | Se uma apostila precisar de conservação ou recuperação de versões, essas funções devem ser configuradas. Classe de armazenamento é uma escolha adicional sobre acesso e custo. EBS forneceria um disco para uma máquina; EFS forneceria arquivos compartilhados. São interfaces diferentes, e o programa precisa saber usar a escolhida.
sqs | A secretaria recebe muitos pedidos de certificado ao fim de um curso. Gerar todos durante a mesma conexão do aluno pode tornar o site lento. A escola separa recebimento do pedido e execução do trabalho. | O site envia uma mensagem com a identificação do pedido. Um consumidor recebe a mensagem, verifica os dados e gera o certificado. O SQS não gera o arquivo: o programa consumidor faz isso. Depois de confirmar sucesso, o programa exclui a mensagem. Durante o processamento, o prazo de invisibilidade reduz novos recebimentos daquela mensagem. | Se o consumidor falhar antes de excluir, a mensagem pode reaparecer. O programa precisa reconhecer pedidos já concluídos para não duplicar efeitos. FIFO trata ordenação por grupo e deduplicação no envio sob condições; não elimina todo risco de efeitos repetidos. SNS atenderia avisos a vários destinos, mas não substitui sozinho esse trabalho em espera.
iam | O programa da escola precisa ler materiais do S3, mas não precisa apagar arquivos nem administrar a conta. O objetivo é conceder uma ação limitada ao componente que realmente a executa. | A equipe define uma role apropriada para o ambiente de execução e políticas para as leituras e recursos necessários. A aplicação usa credenciais temporárias da sessão autorizada. Rede, políticas do recurso e chave criptográfica, quando aplicáveis, também podem influenciar o acesso. | Um login válido não garante que a leitura será permitida. Uma negação ou um limite aplicável pode impedir a operação mesmo com uma concessão em outra política. Não use o root ou uma chave administrativa fixa só porque é mais fácil: essas identidades oferecem poder além da tarefa descrita.
vpc | A escola quer receber visitantes no site, mas não quer que eles se conectem diretamente ao banco. O objetivo é definir caminhos e controles distintos para partes diferentes da aplicação. | A equipe organiza recursos em subnets e prepara rotas compatíveis com a comunicação necessária. O recurso que atende visitantes precisa de um caminho adequado de entrada; o banco precisa de comunicação apenas com componentes autorizados. Security groups e outros controles de tráfego complementam o desenho. | Uma subnet pública tem relação com rota, não é uma permissão automática para todo recurso. Uma conexão que chega ao banco ainda precisa de autenticação e autorização do próprio banco. VPC trata rede; IAM trata operações AWS. Cumprir uma parte do acesso não substitui a outra.
rds | A escola guarda alunos, cursos e matrículas relacionados e seu programa usa consultas SQL de um mecanismo compatível. O objetivo é ter um banco com menos administração de infraestrutura que uma instalação própria na EC2. | A equipe escolhe o mecanismo RDS, prepara capacidade, comunicação e usuários e cria as tabelas. A aplicação consulta e grava registros com suas permissões. A AWS administra as tarefas previstas pelo serviço; a equipe continua definindo os dados e as regras de uso. | Uma opção Multi-AZ ajuda no objetivo de disponibilidade conforme sua modalidade, mas não substitui toda recuperação de um apagamento. Réplicas de leitura atendem outro requisito. Antes de escolher, diferencie continuidade do atendimento, aumento de consultas e retorno a dados de um momento anterior.
lambda | A escola precisa criar uma miniatura quando uma pessoa envia uma foto. O trabalho tem entrada e resultado definidos e não precisa de uma máquina própria aguardando permanentemente o evento. | A equipe escreve a função de transformação, prepara permissões e configura uma integração compatível para acioná-la. Quando chega a entrada, a função executa o código e grava o resultado num armazenamento adequado. O serviço fornece a infraestrutura da execução. | Se o código falhar ou a entrada aparecer novamente, a aplicação precisa de tratamento apropriado. Não confie em memória de uma execução como armazenamento definitivo. A AWS administrar a execução não corrige automaticamente bibliotecas incluídas no pacote nem decide quem pode ler as fotos.
ecs | O serviço de pedidos da escola foi empacotado em uma imagem de container. A equipe precisa executar várias cópias e manter a quantidade desejada, sem iniciar cada cópia manualmente. | A imagem fica num repositório acessível. Uma definição de tarefa descreve a execução e seus recursos. Um serviço ECS mantém tarefas conforme a configuração. Com EC2, a equipe também administra as máquinas; com uma modalidade Fargate compatível, muda a responsabilidade pela capacidade subjacente. | ECR guarda a imagem, mas não mantém sozinho as cópias em execução. Fargate fornece capacidade, mas não substitui a definição de serviço ou a aplicação. Se visitantes precisam de distribuição de tráfego, isso é outra integração a preparar, não consequência automática de guardar a imagem.
ebs | Uma aplicação instalada numa máquina EC2 precisa de um disco para seu sistema e seus arquivos. O objetivo é leitura e escrita pelo sistema operacional, não operações de objetos como no S3. | A equipe escolhe um volume compatível, conecta-o à instância e prepara seu uso no sistema. Os arquivos ficam no volume. Snapshots ajudam a conservar pontos de recuperação, mas sua criação e sua restauração são operações distintas. | Parar a computação pode manter o disco e seu custo. Encerrar a instância exige examinar as políticas de exclusão dos volumes. Instance store é armazenamento local temporário com outro ciclo de vida; não deve receber a única cópia de dados essenciais que precisam sobreviver a essas ações.
cloudwatch | O sistema ficou lento, e a equipe quer perceber o problema e investigar seu comportamento. A pergunta inicial é como ele funciona, não quem realizou uma ação administrativa. | A equipe coleta métricas pertinentes, registros da aplicação e cria um alarme com período e critério definidos. Um aumento de erros pode disparar uma notificação configurada. Logs ajudam a examinar o que o programa registrou durante a ocorrência. | O alarme não explica sozinho a causa nem aplica qualquer correção por padrão. Para investigar quem alterou um recurso, eventos CloudTrail podem ser necessários; para acompanhar propriedades e conformidade de configuração, Config atende outra parte da investigação.
route-53 | O aluno digita um nome de site e precisa chegar ao endereço que atende a escola. A primeira tarefa é resolver esse nome, antes de a aplicação atender a requisição. | A equipe configura a zona e o registro adequados ao domínio e ao destino. Uma consulta DNS obtém as informações de endereço conforme o tipo de registro e a política. O cliente então inicia a comunicação com o destino indicado. | DNS correto não garante que o servidor responde nem que os dados estão autorizados. CloudFront pode distribuir conteúdo; um balanceador pode distribuir conexões; Route 53 informa respostas de nome. Esses recursos podem cooperar, mas resolvem etapas diferentes.
budgets | A escola quer acompanhar sua meta mensal de custo. O objetivo é receber sinal de desvio e agir a tempo, não presumir que a AWS nunca cobrará acima de um valor informado. | A equipe define o orçamento, condições de notificação e destinatários. Quando recebe um aviso, investiga a parte do consumo que aumentou e decide quais mudanças atendem à aplicação. Ações compatíveis podem ser configuradas conforme requisitos e permissões. | O orçamento, por padrão, não funciona como um corte universal e instantâneo de todos os serviços. Cost Explorer ajuda a analisar gastos; a calculadora estima antes do uso. Meta, análise e estimativa respondem perguntas diferentes.
"""
for linha in _DADOS.strip().splitlines():
    nome, *paragrafos = [p.strip() for p in linha.split('|')]
    assert len(paragrafos) == 3 and all(paragrafos) and nome not in CASOS, nome
    CASOS[nome] = paragrafos
