"""Pontes conceituais dos capítulos, antes das tabelas e das regras de prova."""
LICOES = {}
_DADOS = """
1.1 | Separe três coisas: o equipamento físico, o software básico da máquina e o programa usado pelo negócio. Contratar uma máquina transfere a manutenção do equipamento, mas ainda deixa o sistema e o programa para administrar. Contratar uma plataforma transfere mais tarefas; contratar um software pronto muda novamente a divisão. | Por isso, a pergunta principal não é apenas ‘está na nuvem?’. Pergunte o que foi contratado e o que o cliente continua escolhendo, configurando e protegendo. Os modelos abaixo dão nomes a essa diferença.
1.2 | A demanda muda, mas um equipamento comprado permanece na empresa mesmo quando não é utilizado. Obter recursos sob demanda permite aproximar capacidade e necessidade. Isso também reduz a espera para experimentar ou atender um novo projeto. | Diferencie o benefício de sua implementação. A nuvem permite ajustar capacidade, mas a equipe precisa configurar esse ajuste. Também é possível manter recursos ociosos na nuvem e pagar por eles; o benefício não acontece só por mudar o local.
1.3 | Uma aplicação depende de várias partes. Crescer uma delas ajuda apenas se ela for o limite do atendimento. Disponibilidade trata de continuar atendendo; recuperação trata de voltar após uma interrupção. Esses objetivos podem exigir soluções diferentes. | Imagine um banco com cópias: se uma máquina falha, uma alternativa pode ajudar. Se um comando apaga dados e a exclusão chega às cópias, pode ser necessário restaurar um ponto anterior. Isso explica por que redundância, replicação e backup não são sinônimos.
1.4 | Uma revisão técnica precisa avaliar mais que velocidade. Perguntar como operar, proteger, recuperar, dimensionar, pagar e reduzir impacto ambiental revela necessidades diferentes da mesma aplicação. Os pilares organizam essas perguntas. | Uma prática pode beneficiar mais de um pilar. Para escolher na prova, identifique o objetivo destacado. Automatizar um procedimento para melhorar a rotina aponta para operação; preparar recuperação após falha destaca confiabilidade.
1.5 | Tecnologia é apenas uma parte da mudança. A empresa pode ter recursos funcionando, mas faltar equipe preparada, regras de decisão ou procedimentos operacionais. O CAF organiza essas capacidades para não deixar a transformação restrita à instalação de máquinas. | Leia cada perspectiva como um grupo de perguntas e responsáveis. Quem cuida de competências e cultura não realiza a mesma tarefa de quem define padrões técnicos. As fases orientam começar com objetivos, identificar lacunas, experimentar e ampliar.
1.6 | Primeiro conheça a aplicação e suas dependências. Depois decida o que preservar e o que mudar. Mover o mesmo programa, mudar a plataforma de banco e reescrever partes importantes são decisões diferentes, mesmo que o destino seja AWS nos três casos. | A estratégia descreve o tipo de mudança; a ferramenta executa parte do trabalho. Uma ferramenta não decide sozinha se vale manter ou substituir o sistema. Testes e transição dos dados continuam necessários em cada caminho.
1.7 | Um preço isolado não representa toda a operação. Manter tecnologia inclui pessoas, espaço, energia, licenças, capacidade e tarefas de manutenção. Compare cenários completos com hipóteses equivalentes, em vez de misturar necessidades diferentes. | Depois de observar o uso, ajuste capacidade e desperdícios antes de assumir compromissos. Um desconto sobre capacidade desnecessária ainda pode ser gasto desnecessário. Licenças próprias exigem elegibilidade; uma ferramenta de inventário não concede esse direito.
2.1 | Pense em camadas: prédio e equipamento, virtualização, sistema operacional, ambiente de execução, aplicação, identidade e dados. Um serviço pode administrar mais camadas que outro, mas o cliente continua decidindo como usa a solução. | Quando a pergunta menciona uma correção, identifique em qual camada ela acontece. Atualizar Linux de uma máquina EC2 não é a mesma tarefa que corrigir uma biblioteca incluída numa função. O nome do serviço determina parte dessa divisão.
2.2 | Root identifica o controle inicial da conta e possui tarefas especiais. Isso é diferente de uma pessoa com várias permissões administrativas. Separar o acesso cotidiano reduz o alcance de erros e facilita atribuir ações a identidades específicas. | Proteja a autenticação principal e use o acesso cotidiano apropriado. Antes de escolher root para uma tarefa, confira se ela realmente exige essa identidade. Um acesso amplo por IAM não transforma a identidade em root.
2.3 | Uma solicitação possui autor, ação e alvo. Primeiro o sistema verifica a identidade; depois avalia se aquela ação pode ocorrer sobre aquele recurso. Uma identidade autenticada pode continuar sem permissão para realizar a operação. | Um programa que lê um bucket precisa de acesso adequado aos dados e, quando aplicável, à chave de proteção. Usar credenciais temporárias melhora a forma de acesso, mas não elimina políticas e limites. Funcionários e clientes de aplicativos também pedem soluções de identidade diferentes.
2.4 | A conta separa administração e recursos. Várias contas permitem isolar contextos, enquanto a organização fornece ferramentas de gestão comum. Regras centrais limitam possibilidades, mas as identidades de cada conta ainda precisam receber suas permissões. | Não confunda quatro ações: organizar contas, limitar operações, oferecer configurações aprovadas e compartilhar recursos compatíveis. Elas podem fazer parte do mesmo projeto, mas usam objetos e ferramentas diferentes.
2.5 | Proteção durante uma comunicação e proteção de dados armazenados atuam em momentos distintos. Uma conexão protegida evita leitura indevida no caminho; o armazenamento protegido envolve chaves e autorizações para obter os dados depois. | Chave e certificado não são a mesma coisa. O certificado participa da identidade e proteção da conexão; a chave criptográfica é usada nas operações de proteção dos dados. Configurar um deles não prepara automaticamente todas as camadas.
2.6 | Conformidade exige um requisito definido e evidências de atendimento. O provedor demonstra sua parte; o cliente precisa demonstrar decisões e operação que continuam sob sua responsabilidade. Um documento só vale dentro do escopo que descreve. | Separe obter um relatório oficial, avaliar uma configuração e coletar evidências. Esses trabalhos se complementam. A conclusão de uma auditoria não é obtida apenas por abrir uma ferramenta ou usar um serviço certificado.
2.7 | Há três perguntas distintas: ‘como está funcionando?’, ‘quem realizou a ação?’ e ‘como estava configurado?’. Uma métrica responde a comportamento; um evento registra atividade; um histórico de configuração mostra propriedades ao longo do tempo. | Comece pela pergunta e só depois escolha a ferramenta. Se um sistema ficou lento após uma alteração, pode ser necessário correlacionar os três tipos de informação. Registrar dados também exige planejar sua coleta, conservação e acesso.
2.8 | Uma comunicação passa por camadas: caminho de rede, conexão e pedido entendido pela aplicação. Regras nessas camadas examinam informações diferentes. Bloquear uma faixa de endereços não é a mesma tarefa que detectar um padrão malicioso em um campo web. | Use proteção correspondente ao risco e ao recurso. Reduzir sobrecarga, inspecionar pedidos e corrigir código podem ser medidas complementares. Não atribua a uma ferramenta a cobertura que pertence a outra camada.
2.9 | Encontrar algo suspeito começa uma análise. Vulnerabilidade descreve uma fraqueza; ameaça descreve uma possível ação prejudicial; dado sensível descreve conteúdo que exige proteção. Esses achados precisam de interpretações e respostas diferentes. | Considere a sequência detectar, avaliar e responder. Uma ferramenta pode emitir um achado, outra reunir resultados e outra fornecer contexto. Nenhuma indicação deve ser tratada automaticamente como prova completa de um incidente ou de sua correção.
2.10 | Segurança precisa de processos além de ferramentas. Definir quem recebe um aviso, como credenciais são protegidas e quem pode alterar dados evita que uma capacidade técnica fique sem uso adequado. | Relacione cada prática ao risco: autenticação adicional protege a entrada; menor privilégio reduz o poder disponível; comunicação de abuso aciona um canal apropriado. As ações não são intercambiáveis só por pertencerem à segurança.
3.1 | A tela, o comando e o programa são meios de pedir operações ao serviço. O recurso criado não muda de natureza porque a solicitação foi feita de outro modo. A mesma identidade continua limitada pelos controles aplicáveis. | Automatizar é descrever ações para repetir com menos trabalho manual. É necessário tratar resultado e erro, além de fornecer credenciais adequadas. Um arquivo de infraestrutura descreve recursos; uma biblioteca ajuda um programa a chamar operações.
3.2 | Região, zona e ponto de presença descrevem unidades diferentes. Primeiro escolha onde o recurso será criado; depois avalie como ele distribui componentes e atende usuários. Um recurso numa região não ganhou redundância automaticamente. | Várias zonas podem ajudar com falhas locais. Pontos de presença aproximam determinadas funções, como distribuição de conteúdo. Múltiplas regiões pedem decisões adicionais sobre dados, acesso, custos e recuperação; são escolhas de projeto, não apenas nomes no mapa.
3.3 | Uma instância junta processamento, memória, sistema operacional, rede e armazenamento. A imagem prepara a base de software; o tipo define capacidade; a rede define caminhos; regras de tráfego e identidade controlam acessos diferentes. Você instala e mantém o programa que fará o trabalho. | Imagine o sistema da escola: os arquivos ficam num armazenamento, o processo da aplicação usa CPU e memória e os alunos chegam por uma conexão autorizada. Parar suspende a execução em condições aplicáveis; encerrar remove a instância. A decisão sobre volumes e cópias precisa ser examinada separadamente.
3.4 | O atendimento tem duas decisões: quantos recursos existem e para qual deles cada pedido vai. A primeira é capacidade; a segunda, distribuição. Um balanceador trabalha com destinos existentes e não cria sozinho a capacidade de que eles precisam. | Ao aumentar máquinas, verifique se a aplicação pode funcionar em várias cópias e compartilhar ou acessar seus dados adequadamente. Um banco sobrecarregado pode continuar sendo o limite mesmo com mais máquinas web. Escalar exige observar o verdadeiro gargalo.
3.5 | Uma imagem de container empacota software; um container executa esse pacote; um coordenador mantém unidades de execução; uma opção de capacidade fornece o lugar onde elas rodam. Separar essas funções evita confundir ECR, ECS, EKS e Fargate. | Uma função acionada por evento é outra forma de execução: recebe entrada, realiza uma tarefa e devolve ou grava resultado. Não precisa ser a melhor opção para todo programa de longa duração. ‘Sem administrar servidores’ não significa ‘sem configuração’.
3.6 | Escolher computação também envolve o trabalho operacional desejado. Uma oferta simples reduz opções iniciais; uma plataforma facilita implantação; um agendador organiza trabalhos que podem esperar e executar por lote. Essas diferenças importam mais que uma palavra comum no nome. | Para um site pequeno, examine hospedagem e manutenção. Para uma aplicação pronta, examine a plataforma compatível. Para conversões de muitos arquivos, examine a organização de trabalhos. Localização próxima exige outra comparação, incluindo disponibilidade da oferta.
3.7 | Comece pelas perguntas que a aplicação fará aos dados. Relacionar alunos e matrículas pede um modelo; buscar um perfil pelo identificador pede outro; explorar vínculos entre contas pede relações; comparar meses de vendas pede análise. | O modelo do banco e os acessos precisam combinar. Um serviço gerenciado reduz parte da operação, mas você ainda define estruturas, consultas e permissões. Trocar de produto sem avaliar interfaces e padrões de consulta pode não atender à aplicação.
3.8 | Um objeto reúne conteúdo e informações de identificação. O bucket organiza objetos; a chave permite localizar cada um. O nome parecido com uma pasta não transforma S3 num disco local de uma máquina. A aplicação usa operações para enviar e obter conteúdo. | Separe acesso, versões, cópias, retenção e classe de armazenamento. Autorizar uma leitura não altera a durabilidade; manter versões não configura toda replicação; uma classe de arquivo pode exigir espera e custos para recuperação. Cada opção abaixo atende uma decisão própria.
3.9 | Armazenamento em blocos apresenta um disco para o sistema. Armazenamento de arquivos apresenta pastas e arquivos por uma interface de rede. Armazenamento de objetos apresenta conteúdo por operações de serviço. A forma como o programa usa os dados orienta a escolha. | Depois da compatibilidade, avalie compartilhamento, desempenho, disponibilidade e conservação. Um disco para uma máquina não é automaticamente uma pasta para várias. Um backup protege recuperação, mas não transforma sozinho um armazenamento em ambiente de atendimento ativo.
3.10 | Para uma conexão funcionar, o nome deve indicar um destino, o caminho deve existir e os controles devem permitir o tráfego. A identidade da aplicação pode ainda precisar de autorização para os dados. É possível cumprir um desses requisitos e falhar em outro. | Separe rede virtual, ligação entre redes, acesso remoto, resolução de nomes e distribuição de conteúdo. Uma CDN mantém e entrega conteúdo conforme regras; aceleração de rede encaminha tráfego; DNS informa destinos. As três funções não são a mesma etapa.
3.11 | Um dado bruto precisa de estrutura e significado antes de responder bem a uma pergunta. Preparação padroniza; catálogo descreve; consulta seleciona e agrega; processamento executa transformações; visualização apresenta resultados. | Uma fonte contínua pode exigir processamento enquanto os registros chegam. Uma análise mensal pode trabalhar sobre arquivos acumulados. Escolha a ferramenta pela etapa e pela forma de chegada dos dados, e não apenas pela categoria ‘analytics’.
3.12 | Diferencie usar uma função pronta, construir um modelo próprio e usar um modelo generativo existente. Na função pronta, você solicita uma transformação específica. No modelo próprio, precisa preparar treinamento e avaliação. Na geração, fornece instrução e contexto para uma resposta. | Em todos os casos, dados e resultados exigem cuidado. Precisão não é garantida; acesso aos documentos deve ser autorizado; produzir uma resposta não a transforma em evidência. O requisito da tarefa e o escopo da prova orientam qual produto estudar.
3.13 | Enviar uma solicitação e executar seu trabalho não precisam acontecer no mesmo instante. Uma fila conserva trabalho; uma notificação avisa interessados; um evento descreve algo ocorrido; um fluxo coordena tarefas. Essa separação reduz dependências imediatas. | Pense num certificado: o site confirma que recebeu o pedido, a fila guarda a tarefa e um consumidor gera o arquivo depois. Se o processamento falhar, receber de novo pode ser necessário. A aplicação precisa evitar que repetição crie efeitos indevidos.
3.14 | Um serviço de aplicação normalmente já oferece uma função do negócio, como atendimento ou envio de mensagens, mas ainda precisa de configuração e integração. A empresa define identidades, conteúdo e os sistemas relacionados àquela experiência. | Não confunda e-mail de uma aplicação com caixa postal de funcionários, nem transmissão de software com armazenamento de arquivos. Dispositivos físicos também precisam de software e proteção. Cada produto abaixo atende uma necessidade concreta diferente.
3.15 | Uma versão do programa passa por preparação, verificação e publicação. Um processo automatizado conecta essas etapas, mas realiza o que foi definido pela equipe. Depois, observar a execução é um trabalho diferente de construir a versão. | Testes precisam existir e verificar comportamentos relevantes. Rastreamentos ajudam a localizar etapas lentas quando a aplicação emite dados adequados. Nenhuma ferramenta de desenvolvimento substitui a definição da regra de negócio ou a validação da mudança.
3.16 | Operar um ambiente inclui repetir configurações, executar procedimentos, acompanhar mudanças e verificar condições de saúde. Governança define e acompanha regras comuns. São tarefas complementares, não uma única ação realizada por qualquer serviço de administração. | Descrever infraestrutura ajuda a repetir recursos. Preparar máquinas para administração ajuda a operar tarefas. Registrar alterações ajuda a investigar. Comece pela ação desejada e pelos recursos envolvidos, então escolha a ferramenta que tem essa função.
3.17 | Migração é uma sequência, não apenas uma cópia. Descubra componentes e dependências, escolha a mudança, prepare origem e destino, transfira ou replique, teste e realize a transição. Arquivos, máquinas e bancos podem seguir ferramentas diferentes. | Avalie estrutura e dados separadamente. Um banco de outra tecnologia pode exigir conversão; um programa pode precisar de ajustes; uma conexão pode precisar de mudança. Testar o conjunto evita concluir que a migração terminou só porque os dados chegaram.
3.18 | Um nome pouco conhecido precisa ser lido pelo trabalho que realiza. A categoria reúne funções distintas e também referências históricas. Aprender a classificar o problema ajuda mais que decorar todos os nomes sem contexto. | Examine função, compatibilidade e status. Fora do escopo do exame não significa que um produto é recomendável ou está disponível hoje; não listado também não significa uma garantia sobre futuras questões. Priorize o guia oficial e use o restante como referência.
4.1 | O serviço mede uma unidade de consumo ou capacidade, não necessariamente pessoas usando seu sistema. Tempo de máquina, espaço de dados, chamadas e transferência são dimensões diferentes. Uma aplicação pode reunir várias cobranças ao mesmo tempo. | Antes de calcular, identifique o recurso, a unidade e a condição. Parar computação pode manter volumes; remover uma aplicação pode manter cópias; uma chamada pode consumir unidades conforme seu tamanho. O modelo de cobrança evita suposições de custo zero.
4.2 | Uma opção de compra combina preço com condições. Uso flexível, compromisso de gasto, possibilidade de interrupção, capacidade e dedicação física são requisitos separados. Uma opção que reduz preço pode mudar uma condição importante do trabalho. | Primeiro descreva se a tarefa pode parar, quanto uso é previsível e se precisa de uma modalidade específica de hardware ou licença. Só então compare a compra. Reserva de capacidade e desconto não são sinônimos, e um compromisso pode permanecer mesmo após reduzir recursos.
4.3 | Veja a aplicação como um conjunto de recursos cobrados separadamente. A máquina executa, o volume conserva dados, a cópia protege recuperação e a rede move informações. Parar uma parte não necessariamente encerra as outras. | Procure o que permanece provisionado ou conservado. Isso explica por que limpar um ambiente exige revisar recursos associados, e não apenas desligar o programa. Confira as condições de cada serviço, sem aplicar uma regra universal de transferência ou armazenamento.
4.4 | O momento da pergunta muda a ferramenta: antes do uso, há hipóteses de consumo; depois do uso, há registros; durante o acompanhamento, há metas e avisos. Estimativa, análise e orçamento se complementam, mas não entregam o mesmo resultado. | Uma previsão não é garantia, e um alerta não é um teto rígido universal. Para agir, identifique o recurso que gera custo, suas condições e o impacto de mudar. Relatórios mais detalhados ajudam a investigar, mas não escolhem sozinhos a arquitetura.
4.5 | Suporte é uma relação de assistência com cobertura definida. A organização informa o problema, seu impacto e o contexto; o atendimento responde e acompanha conforme a oferta. A equipe continua operando as partes que não foram contratadas para administração externa. | Separe resposta inicial de resolução. Uma primeira resposta rápida pode iniciar uma investigação longa. Também diferencie exemplos do guia do exame de nomes comerciais atuais: a pergunta deve ser interpretada dentro do contexto descrito.
4.6 | Aprender uma função, esclarecer uma dúvida, comprar uma oferta e contratar execução são trabalhos diferentes. Um canal comunitário, uma documentação, uma loja e uma equipe profissional têm responsabilidades e condições distintas. | Escreva primeiro o resultado desejado. Depois escolha a fonte ou serviço com esse papel e valide sua aplicabilidade. Uma orientação publicada não é compromisso de executar o projeto nem promessa de um prazo de atendimento.
"""
for linha in _DADOS.strip().splitlines():
    sec, *paragrafos = [p.strip() for p in linha.split('|')]
    assert len(paragrafos) == 2 and all(paragrafos) and sec not in LICOES, sec
    LICOES[sec] = paragrafos
