"""Sequências conceituais autorais; não são tutoriais de console ou comandos."""
PASSOS = {}
_DADOS = """
ec2 | Escolha uma imagem de sistema e a capacidade da máquina. Essa combinação define a base em que o programa executará. | Prepare disco, conexão de rede e permissões. Instale a aplicação e permita apenas os acessos de que ela precisa. | Observe a execução e mantenha o software atualizado. Decida separadamente o destino da máquina e dos dados ao parar ou encerrar.
ec2-auto-scaling | Defina a configuração das máquinas e a quantidade mínima, desejada e máxima do grupo. | Escolha condições que ajustam a quantidade, como uma métrica de utilização. O grupo cria ou remove máquinas dentro desses limites. | Observe se a capacidade acompanha a demanda. A aplicação deve funcionar com cópias que podem ser substituídas.
elastic-load-balancing | Defina os recursos que podem atender pedidos e como verificar sua saúde. | Configure a entrada de tráfego e seu encaminhamento aos destinos. O balanceador escolhe destinos conforme suas regras e condições. | Uma verificação malsucedida pode retirar um destino do atendimento. Corrija a causa e acompanhe a capacidade dos recursos restantes.
lambda | Escreva uma função que realize uma tarefa delimitada e defina como ela será chamada. | Configure os recursos, os acessos e a integração que fornece a entrada. A AWS inicia a execução quando recebe a chamada ou o evento. | Guarde resultados que precisam durar em um recurso apropriado e trate falhas. Não dependa de execução infinita nem de memória preservada entre chamadas.
ecs | Guarde a imagem da aplicação num repositório acessível e descreva como executar seus containers. | Escolha a capacidade de execução e configure o serviço quando precisar manter uma quantidade de tarefas funcionando. | ECS acompanha o estado desejado. A aplicação, a conexão e as permissões ainda precisam estar corretas.
eks | Defina um ambiente Kubernetes e a forma de fornecer capacidade para os containers. | Publique as descrições da aplicação e suas necessidades. Kubernetes coordena o posicionamento e a quantidade de unidades de execução. | Acompanhe aplicação e recursos. A divisão do trabalho de administração depende da modalidade escolhida.
fargate | Descreva os containers pelo ECS ou EKS e selecione uma modalidade de execução compatível com Fargate. | Defina capacidade, comunicação e permissões. Fargate fornece a infraestrutura de execução sem você administrar diretamente as máquinas. | Observe os containers e seus resultados. A AWS administrar servidores não elimina a responsabilidade pelo código e pelos acessos.
ecr | Crie um repositório e envie uma imagem da aplicação, identificando sua versão. | Autorize os ambientes que devem baixar a imagem. O ambiente de execução obtém o pacote necessário. | Publique novas versões e administre sua conservação. O repositório guarda imagens; outro componente executa o programa.
elastic-beanstalk | Escolha uma plataforma compatível e prepare o pacote da aplicação. | Crie um ambiente com opções de capacidade, acesso e implantação. Beanstalk organiza recursos AWS para atender essa configuração. | Envie versões e acompanhe a saúde da aplicação. Código, escolhas operacionais e recursos cobrados continuam exigindo atenção.
lightsail | Escolha uma oferta e um modelo de software compatíveis com seu site ou aplicação. | Crie o recurso e prepare o conteúdo, a conexão e o domínio quando necessário. | Mantenha o software protegido e acompanhe o consumo. O pacote simplifica escolhas, mas continua tendo limites e responsabilidades.
batch | Prepare o programa que realiza um trabalho e descreva sua execução. | Envie trabalhos a uma fila e configure o ambiente de computação. Batch agenda as execuções conforme as necessidades e a capacidade. | Acompanhe resultados e falhas. Cada trabalho precisa gerar o resultado previsto e permitir tratamento de execução malsucedida.
outposts-local-zones-wavelength | Identifique onde o processamento precisa ocorrer e qual tempo de comunicação é aceitável. | Compare as localizações e os serviços disponíveis em cada oferta. Não confunda equipamento no cliente com infraestrutura em outro local. | Planeje comunicação e operação conforme a opção. Confira restrições antes de supor que toda região e toda oferta atendem o cenário.
s3 | Crie um bucket para organizar objetos e defina quem pode enviar e ler dados. | Envie um objeto com uma chave que o identifique. A aplicação faz operações autorizadas para gravar, obter ou excluir conteúdo. | Escolha proteção, conservação e classe de armazenamento. Apagar um objeto, guardar uma versão e manter um arquivo são decisões distintas.
s3-classes-de-armazenamento | Descubra com que frequência o conteúdo será acessado e quanto tempo pode esperar por recuperação. | Compare armazenamento, acesso, recuperação e duração mínima. Selecione a classe compatível com o conjunto de requisitos. | Use regras de ciclo de vida quando apropriado e acompanhe o custo completo. Uma economia de armazenamento pode trazer despesas ou espera de recuperação.
ebs | Escolha a capacidade e o comportamento de armazenamento e crie um volume compatível com a máquina. | Conecte e prepare o disco no sistema operacional. A aplicação passa a ler e gravar arquivos nele. | Planeje cópias e exclusão. O volume pode continuar existindo e sendo cobrado mesmo quando a máquina deixa de executar.
efs | Crie um sistema de arquivos e prepare os pontos de acesso de rede necessários. | Permita que máquinas compatíveis e autorizadas montem o armazenamento. Elas passam a acessar um conjunto compartilhado de arquivos. | Administre permissões, desempenho e proteção dos dados. Compartilhar não significa liberar o conteúdo a qualquer máquina.
fsx | Identifique o sistema de arquivos que a aplicação espera e escolha a modalidade correspondente. | Prepare identidade, conexão e armazenamento. Os clientes compatíveis acessam os arquivos por sua interface prevista. | Planeje disponibilidade, cópias e capacidade. Cada modalidade tem seus próprios recursos e limites.
storage-gateway | Descubra se a aplicação local precisa de arquivos, volumes ou interface de fitas. | Prepare um gateway compatível, seu armazenamento local e sua conexão com a AWS. A aplicação usa a interface apresentada. | Acompanhe envio, cache e conservação conforme a modalidade. O gateway conecta armazenamento; não migra sozinho o programa.
aws-backup | Selecione recursos compatíveis e defina periodicidade, destinos e retenção das cópias. | Atribua os recursos ao plano. O serviço executa operações conforme a agenda e as permissões. | Teste a restauração e confira se os dados recuperados servem à aplicação. Sucesso de cópia e sucesso de recuperação são verificações diferentes.
elastic-disaster-recovery | Prepare os servidores compatíveis, permissões e destino de replicação. | Mantenha os dados replicados e realize testes de recuperação na AWS. A aplicação precisa ser validada com suas dependências. | Durante uma interrupção, acione o procedimento planejado e confira o atendimento. Replicação é a preparação, não a operação completa do negócio.
rds | Escolha um mecanismo de banco compatível com a aplicação e suas necessidades de capacidade e disponibilidade. | Prepare conexão e identidade. Crie as estruturas dos dados e faça a aplicação realizar operações autorizadas. | Acompanhe desempenho, retenção e recuperação. A AWS administra tarefas previstas, mas a modelagem e o uso dos dados continuam com o cliente.
aurora | Escolha a compatibilidade MySQL ou PostgreSQL e a modalidade que atende à aplicação. | Defina as instâncias ou opções de capacidade, os acessos e os pontos de conexão do conjunto. | Distribua leitura e escrita de forma compatível e planeje recuperação. Compatibilidade e arquitetura precisam ser avaliadas antes de migrar.
dynamodb | Descreva os registros e como a aplicação precisa buscá-los. Escolha as chaves a partir desses acessos. | Crie uma tabela com modalidade de capacidade e índices adequados. A aplicação grava e consulta itens pelas operações compatíveis. | Observe consumo e distribuição do acesso. Alterar o padrão de consulta pode exigir mudanças de modelagem, não apenas mais capacidade.
elasticache | Identifique uma consulta ou dado que pode ser reutilizado e defina por quanto tempo a cópia serve. | Prepare um mecanismo compatível e faça a aplicação consultar e atualizar o cache conforme seu desenho. | Trate conteúdo desatualizado, falhas e expiração. Um cache acelera acesso, mas não define sozinho a verdade dos dados.
memorydb | Avalie a compatibilidade da aplicação e a necessidade de manter dados em memória com durabilidade. | Prepare o banco e a conexão autorizada. A aplicação usa as estruturas e operações compatíveis. | Planeje disponibilidade e recuperação. Não transfira para este produto as suposições de um cache temporário nem de todo banco relacional.
redshift | Organize fontes e o modelo de dados para as perguntas analíticas desejadas. | Prepare o ambiente e carregue ou disponibilize dados por mecanismos compatíveis. Execute consultas para obter agregações e comparações. | Acompanhe qualidade, capacidade e atualização dos dados. A análise histórica não substitui automaticamente o banco de operações da aplicação.
documentdb | Avalie as operações e estruturas que sua aplicação usa na interface de documentos. | Prepare um ambiente compatível e grave registros estruturados. A aplicação consulta campos e documentos por suas operações. | Teste as diferenças de compatibilidade e planeje cópias e acessos. O nome documento não significa armazenar qualquer arquivo PDF como num bucket.
neptune | Identifique quais entidades e relações precisam ser representadas. | Grave nós e conexões e escreva consultas que percorram essas relações. | Avalie se as respostas atendem ao problema. O banco permite explorar relações; o julgamento de fraude ou outra regra ainda precisa ser definido.
keyspaces-timestream-e-outros | Identifique se os dados são registros Cassandra, valores com horários ou outro modelo especializado. | Compare compatibilidade e disponibilidade da oferta apropriada; a ficha não descreve um único banco para todos os casos. | Modele e consulte os dados conforme a interface escolhida. Confira as observações sobre serviços restritos ou encerrados.
vpc | Defina a faixa de endereços e organize segmentos de rede para os recursos. | Configure caminhos de comunicação e regras de tráfego. Ter um endereço não basta sem rota e controles apropriados. | Teste as conexões necessárias e bloqueie as desnecessárias. Identidade da aplicação e permissões de dados são controles adicionais.
vpc-peering-transit-gateway-e-endpoints | Descreva quem precisa comunicar-se com quem: duas redes, muitas redes ou um serviço específico. | Escolha a conexão pertinente e configure suas associações, rotas e controles. | Teste o caminho autorizado. Não suponha trânsito entre redes ou permissão a dados apenas porque existe uma conexão.
site-to-site-vpn-e-client-vpn | Identifique se precisa ligar redes ou permitir acesso de dispositivos de usuários. | Prepare a modalidade de VPN correspondente, autenticação quando aplicável e rotas para os recursos necessários. | Verifique comunicação e permissões. Um túnel protegido não torna toda aplicação automaticamente acessível.
direct-connect | Planeje o local e a conexão física compatível com o ambiente da empresa. | Configure interfaces e rotas de acesso aos recursos desejados. A comunicação usa a conectividade planejada. | Planeje caminhos alternativos e proteção dos dados. Conexão dedicada não significa criptografia automática ou ausência de falhas.
route-53 | Determine o nome que os usuários consultarão e o destino que deve atender. | Configure os registros e a política de resposta pertinente. O resolvedor DNS consulta informações para localizar o destino. | Acompanhe mudanças e saúde quando aplicável. Resolver o nome não confirma que a aplicação está respondendo corretamente.
cloudfront | Defina a origem e quais conteúdos ou caminhos a distribuição deve atender. | Configure regras de entrega, cache e acesso. Os pedidos podem ser atendidos por cópias ou encaminhados à origem conforme essas regras. | Planeje atualização do conteúdo e proteção da origem. Conteúdo privado ou dinâmico exige condições adequadas de acesso e cache.
global-accelerator | Defina destinos compatíveis e o comportamento de atendimento entre eles. | Prepare os pontos de entrada e o encaminhamento pela rede AWS conforme a configuração e a saúde observada. | Observe o resultado nas conexões. O serviço encaminha tráfego; ele não mantém cópias dos arquivos da aplicação.
api-gateway | Descreva as operações que outro programa pode solicitar e seus dados de entrada. | Configure uma API e suas integrações e controles. Cada chamada segue para o componente que realiza o trabalho. | Observe falhas e acesso. A API não cria por si só o banco nem as regras que aprovam ou recusam uma operação.
iam | Identifique a pessoa ou programa, a ação necessária e o recurso sobre o qual ela acontecerá. | Configure a identidade e políticas adequadas, considerando limites e relações de confiança aplicáveis. | A solicitação é avaliada pelos controles. Falta de acesso pode ser problema de permissão, não impossibilidade do serviço.
iam-identity-center | Conecte ou configure a fonte de identidades da força de trabalho. | Atribua acessos a contas e aplicações, definindo permissões pertinentes a cada atribuição. | A pessoa entra pelo portal e seleciona os acessos autorizados. A sessão não dá poder sobre contas que não foram atribuídas.
cognito | Escolha como cadastrar e autenticar usuários do aplicativo. | Integre o aplicativo com o recurso de identidade adequado e valide as informações de autenticação. | Aplique as regras de autorização no uso da aplicação. Saber quem entrou não permite mostrar os dados de qualquer outra pessoa.
directory-service | Identifique o diretório existente e o tipo de integração requerido pelas aplicações. | Escolha uma modalidade que cria um diretório ou usa uma relação com o ambiente existente, conforme sua função. | Prepare conexões e confiança e teste a autenticação. As modalidades não têm a mesma divisão de responsabilidades.
kms | Escolha ou crie uma chave compatível e defina quem pode administrá-la e utilizá-la. | Configure o recurso ou a aplicação para usar a proteção apropriada. As operações de chave são avaliadas conforme as autorizações. | Planeje uso, auditoria e ciclo de vida da chave. Perder acesso à chave pode afetar o acesso aos dados protegidos.
cloudhsm | Avalie os requisitos de controle criptográfico e prepare os módulos compatíveis. | Administre usuários e chaves na solução e integre o software às operações necessárias. | Planeje disponibilidade e proteção operacional. Controle dedicado exige trabalho que não deve ser confundido com a abstração de KMS.
certificate-manager | Identifique os nomes que precisam ser cobertos pelo certificado e a integração desejada. | Solicite ou disponibilize um certificado compatível e atenda à validação prevista. Associe-o ao ponto de conexão. | Acompanhe validade e condições de renovação. Emitir o certificado e configurar o recurso para usá-lo são etapas diferentes.
secrets-manager-e-parameter-store | Separe valores sensíveis e parâmetros comuns de configuração. | Guarde os valores na ferramenta compatível e autorize apenas quem precisa obtê-los. A aplicação lê o valor ao executar. | Planeje atualização e rotação conforme a integração. Guardar uma senha não muda sozinho a senha do sistema externo.
shield | Identifique os recursos e o tipo de exposição que precisam de proteção contra sobrecarga. | Avalie a modalidade e sua cobertura para a arquitetura. Os mecanismos de proteção atuam conforme suas condições. | Observe eventos e prepare resposta. Proteção contra DDoS não corrige vulnerabilidades do código nem substitui todos os controles de aplicação.
waf | Identifique o ponto web compatível e o padrão de pedidos que deseja permitir, observar ou bloquear. | Crie regras e associe o conjunto ao recurso. Os pedidos são inspecionados conforme a configuração. | Acompanhe resultados e ajuste regras. Um bloqueio incorreto pode afetar usuários legítimos; a correção do programa também precisa ser planejada.
firewall-manager-e-network-firewall | Separe a necessidade de administrar políticas da necessidade de inspecionar tráfego. | Use Firewall Manager para políticas compatíveis da organização; avalie Network Firewall para o caminho de rede que precisa de inspeção. | Configure escopo e verifique o efeito dos controles. As duas ferramentas não executam a mesma função.
guardduty | Habilite os recursos e as fontes de detecção compatíveis com seu ambiente. | O serviço analisa sinais e produz achados quando identifica condições suspeitas. | Investigue o contexto e defina uma resposta. Um achado é uma indicação para análise, não uma ação de bloqueio universal.
inspector | Prepare e habilite a avaliação dos tipos de recurso compatíveis. | O serviço identifica vulnerabilidades e riscos cobertos pela avaliação. | Priorize correções e verifique o resultado. Encontrar uma vulnerabilidade não instala a atualização necessária.
macie | Defina os dados S3 compatíveis que precisam de avaliação e a configuração de descoberta. | O serviço examina conteúdo conforme sua cobertura e produz resultados sobre possíveis dados sensíveis. | Revise achados e corrija exposição quando necessário. A descoberta não anonimiza os arquivos automaticamente.
detective | Prepare as fontes e o ambiente de investigação compatível. | Use as relações de atividades, identidades e recursos para entender o contexto de um alerta. | Compare evidências e registre conclusões da investigação. A ferramenta ajuda a analisar; a decisão e a resposta continuam precisando de responsáveis.
security-hub | Defina os ambientes, controles e fontes compatíveis que participarão da visão de segurança. | Reúna achados e resultados de controles para acompanhar a postura dos recursos. | Priorize problemas e configure respostas quando apropriado. Centralização não significa correção automática de todo achado.
artifact | Identifique o relatório ou acordo que atende à avaliação pretendida. | Acesse o documento disponível sob as condições aplicáveis e examine seu escopo. | Use o documento junto às evidências do cliente. Um relatório do provedor não demonstra sozinho os controles da aplicação.
audit-manager | Defina uma avaliação e os controles que precisam de evidências. | Organize coleta de evidências compatíveis e complemente o material necessário. | Revise a avaliação para a auditoria. A ferramenta não certifica automaticamente a organização nem dispensa controles manuais.
cloudwatch | Escolha quais medidas e registros ajudam a observar o problema da aplicação. | Configure coleta, visualizações e condições de alarme. Dados são acompanhados dentro dos períodos e critérios definidos. | Investigue mudanças e acione a resposta planejada. Um número isolado não explica a causa de toda falha.
cloudtrail | Determine quais atividades e tipos de evento precisam ser registrados e conservados. | Configure a cobertura e consulte eventos para examinar ações realizadas por identidades. | Proteja e analise os registros. Um evento de API não é o mesmo que uma linha de log emitida dentro do seu programa.
config | Selecione os recursos e configurações compatíveis que precisam de acompanhamento. | Registre mudanças e aplique regras de avaliação para requisitos definidos. | Investigue não conformidades e configure remediação quando apropriado. Avaliar uma configuração e corrigi-la são operações diferentes.
systems-manager | Prepare as máquinas para torná-las nós gerenciados, com requisitos de agente, rede e identidade atendidos. | Escolha a ferramenta operacional correspondente, como sessão, comando ou atualização. Execute a ação autorizada. | Confira resultados e falhas em cada alvo. Administrar muitas máquinas não torna toda operação segura sem planejamento.
cloudformation | Escreva um template com recursos, parâmetros e dependências do ambiente. | Crie ou atualize uma stack. A ferramenta realiza operações sobre os recursos conforme a descrição e as políticas. | Examine mudanças e possíveis efeitos nos dados. Repetir infraestrutura não significa que qualquer alteração pode ser desfeita sem risco.
organizations | Organize contas e unidades conforme a separação de trabalho da empresa. | Aplique políticas e recursos de administração central compatíveis com os objetivos. | Confira o alcance das regras e mantenha permissões nas contas. Uma restrição central não concede acesso a uma identidade.
control-tower | Defina a base de várias contas e os controles necessários para seu ambiente. | Estabeleça a landing zone e use os mecanismos compatíveis de criação e governança das contas. | Acompanhe controles e mantenha as aplicações dentro das regras. A base não resolve toda configuração específica dos sistemas.
service-catalog-e-ram | Identifique se quer oferecer uma configuração aprovada ou compartilhar um recurso já existente. | Use produtos e portfólios do catálogo no primeiro caso; compartilhamentos compatíveis no RAM no segundo. | Verifique acessos e alcance. Um produto provisionável e um recurso compartilhado são objetos diferentes.
trusted-advisor | Consulte verificações compatíveis com seu ambiente e seu nível de acesso. | Leia o problema e a recomendação associados ao recurso. Compare-os com os requisitos reais da aplicação. | Faça a mudança adequada e acompanhe o resultado. Não remova um recurso apenas por uma recomendação sem avaliar seu papel.
health-dashboard | Consulte a visão geral ou específica da conta conforme a investigação. | Leia os eventos e identifique os recursos e prazos relevantes. | Execute as ações pertinentes e acompanhe a aplicação com suas próprias ferramentas de observação.
compute-optimizer-service-quotas-e-license-manager | Descubra se o problema é dimensão do recurso, limite de uso ou administração de licença. | Consulte a ferramenta pertinente e os dados que fundamentam a decisão. | Ajuste recursos, solicite aumento elegível ou revise licenças conforme o caso. Essas ações não são intercambiáveis.
athena | Identifique a fonte compatível e descreva a estrutura dos dados. | Escreva uma consulta para responder a uma pergunta concreta e execute-a sobre os dados necessários. | Leia o resultado e examine o volume consultado. Dados mal interpretados não se tornam corretos só porque a consulta executou.
glue | Defina fontes, estruturas e a transformação necessária para preparar os dados. | Catalogue ou descubra estruturas e execute trabalhos de transformação compatíveis. | Verifique o conteúdo de saída e suas permissões. Padronizar nomes de campos não garante qualidade de todo registro.
kinesis | Defina quem produz registros e quem precisa processá-los ou recebê-los num destino. | Escolha o produto apropriado para fluxo, processamento ou entrega e envie os dados pelas interfaces compatíveis. | Acompanhe consumo, conservação e destino dos registros. Cada produto tem condições diferentes de processamento e espera.
emr | Escolha a ferramenta de processamento e prepare o código e os dados de entrada. | Execute o trabalho numa modalidade EMR compatível e com os acessos necessários. | Valide os dados de saída e acompanhe uso de capacidade. O ambiente executa o processo; a lógica de análise deve estar correta.
quicksight | Conecte uma fonte compatível e prepare um conjunto de dados com significado definido. | Crie visualizações que respondam às perguntas desejadas e controle quem pode vê-las. | Confira atualização e interpretação dos indicadores. Uma visualização bonita não garante um resultado correto.
opensearch | Prepare dados e defina como eles serão indexados para busca. | Envie registros e consulte palavras, campos ou relações compatíveis com o índice. | Acompanhe atualização, armazenamento e acesso. A ferramenta só busca no conteúdo efetivamente disponibilizado ao ambiente.
lake-formation-msk-e-outros | Separe a necessidade de governar dados da necessidade de fluxos Kafka ou integrações especializadas. | Avalie o produto específico e prepare suas fontes, identidades e destinos compatíveis. | Confira o resultado e a oferta atual. A categoria reúne ferramentas distintas, não uma solução única.
sagemaker-ai | Defina a tarefa, prepare dados adequados e escolha o processo de desenvolvimento do modelo. | Treine e avalie o modelo com critérios pertinentes. Separe dados e etapas de forma adequada ao método escolhido. | Disponibilize inferência compatível e acompanhe qualidade. Um resultado de treinamento não garante bom desempenho para toda entrada futura.
bedrock | Escolha um modelo disponível e descreva a tarefa e o contexto que pretende enviar. | Integre a aplicação pelas interfaces e autorizações compatíveis. Avalie a resposta produzida para a finalidade desejada. | Controle dados, custos e qualidade. A geração de uma resposta não é comprovação de que o conteúdo está correto.
amazon-q | Escolha o produto do assistente conforme desenvolvimento ou conhecimento corporativo. | Prepare o contexto e as integrações autorizadas e faça uma solicitação relacionada à tarefa. | Revise a resposta antes de usar. Um assistente não deve ter acesso presumido a todos os documentos nem substituir a validação do trabalho.
servicos-de-ia-prontos | Identifique a transformação desejada, como fala para texto ou extração de campos. | Escolha o serviço específico e forneça uma entrada compatível com as permissões necessárias. | Avalie o resultado e trate erros. Produtos de tradução, voz, texto e imagem não são substitutos universais uns dos outros.
sqs | O produtor envia uma mensagem descrevendo um trabalho, como emitir um certificado. A fila guarda a mensagem; ela ainda não executou o trabalho. | O consumidor recebe a mensagem e realiza a tarefa. Durante o prazo de invisibilidade, a mensagem fica indisponível para novos recebimentos. | Após sucesso, o consumidor exclui a mensagem. Se falhar sem excluir, ela pode reaparecer; trate repetições e encaminhamento para uma fila de falhas configurada.
sns | Defina um tópico e os destinos que devem receber notificações compatíveis. | Publique uma mensagem. O serviço encaminha a notificação conforme assinaturas e filtros configurados. | Cada destinatário realiza seu próprio trabalho e precisa tratar falhas. Publicar uma mensagem não comprova sucesso em todos os sistemas interessados.
eventbridge | Defina a origem dos eventos e o critério que distingue cada situação. | Configure regras e destinos compatíveis. Um evento que corresponde à regra é encaminhado ao destino apropriado. | Observe entrega e ação do destino. Encaminhar o acontecimento e concluir o trabalho de negócio são etapas diferentes.
step-functions | Descreva etapas, decisões e tratamento de falhas do processo. | Inicie uma execução com seus dados de entrada. O fluxo coordena as etapas e os componentes que realizam as tarefas. | Examine estado e resultado da execução. A coordenação não escreve automaticamente o código de cada tarefa.
amazon-mq | Avalie a tecnologia e os protocolos de mensagens usados pela aplicação existente. | Prepare um broker compatível e conecte produtores e consumidores autorizados. | Teste comportamento, falhas e disponibilidade. Preservar interface não dispensa validar a migração do sistema.
cli-sdk-e-cloudshell | Escolha comandos, biblioteca de programação ou terminal conforme a forma de trabalho. | Configure identidade e ambiente e solicite a operação AWS desejada. | Leia o resultado ou erro e trate-o no processo. Alterar a ferramenta de acesso não altera automaticamente a permissão da identidade.
code-services | Defina as etapas e os arquivos necessários para construir e verificar uma versão. | Execute construção e organize a sequência de entrega nas ferramentas compatíveis. | Valide os resultados antes de publicar e acompanhe a execução. A automação segue suas instruções, inclusive quando elas estiverem incorretas.
x-ray | Prepare a aplicação para emitir dados de rastreamento nas partes que precisa observar. | Acompanhe o caminho de uma requisição e os tempos de cada segmento registrado. | Investigue a etapa problemática e valide a correção. Um rastreamento não observa automaticamente todo detalhe que não foi instrumentado.
amazon-connect | Descreva como o cliente deve entrar e como suas solicitações serão encaminhadas. | Configure fluxos, canais e atendimento compatíveis com a operação. | Observe filas e qualidade do atendimento. Plataforma de contato e regras do sistema de cadastro precisam ser integradas quando necessário.
ses | Verifique a identidade de envio e prepare as condições de acesso e volume aplicáveis. | Faça a aplicação solicitar o envio de uma mensagem com conteúdo e destinatário pertinentes. | Acompanhe devoluções, reclamações e reputação. Aceitar uma solicitação de envio não garante chegada à caixa principal do destinatário.
workspaces-e-appstream | Identifique se o usuário precisa de desktop completo, aplicação transmitida ou navegação corporativa. | Prepare a modalidade, identidades e software necessários. A pessoa inicia uma sessão autorizada. | Administre acesso e experiência. Cada modalidade oferece uma experiência diferente de trabalho remoto.
amplify-e-appsync | Separe a necessidade de publicar a interface da necessidade de uma API e de dados. | Prepare a hospedagem e as integrações compatíveis com o projeto, escolhendo a ferramenta apropriada para cada função. | Teste autenticação, dados e entrega. Uma interface publicada não demonstra que todas as operações internas funcionam corretamente.
iot-core-e-greengrass | Prepare identidade e software dos dispositivos que vão comunicar-se. | Configure os canais e as permissões para dados e comandos. Avalie processamento local separadamente quando necessário. | Acompanhe conexão e resultado. Equipamento conectado não implica que qualquer análise ou atualização já esteja implementada.
discovery-migration-hub-e-evaluator | Levante recursos, dependências e necessidades do ambiente atual. | Use a ferramenta compatível para descoberta, avaliação de custos ou acompanhamento da mudança. | Organize o plano e valide as hipóteses. Inventário e acompanhamento não transferem sozinhos a aplicação.
application-migration-service | Prepare servidores compatíveis e o destino de replicação. | Replique dados e teste a execução no destino com as dependências da aplicação. | Planeje e realize a troca do ambiente em uso. Mover o servidor não dispensa validar rede, dados e integrações.
dms-e-sct | Avalie origem, destino e necessidade de conversão da estrutura do banco. | Converta o que for suportado e mova dados com o processo compatível, incluindo alterações quando necessário. | Teste aplicação e consistência antes da transição. Copiar registros e adaptar consultas são trabalhos diferentes.
snow-family | Entenda a necessidade histórica de transportar dados quando a conexão era inadequada. | No processo compatível com a oferta, dados eram copiados para um dispositivo físico e enviados para importação. | Confira restrições e alternativas atuais. O exemplo não significa disponibilidade para um novo cliente hoje.
datasync-e-transfer-family | Separe sincronização entre locais de recebimento por protocolo de arquivo. | Prepare a ferramenta correspondente, seus locais e sua autorização; então execute a transferência compatível. | Compare resultados e trate falhas. Arquivos movidos não equivalem à migração completa das aplicações que os usam.
cost-explorer | Selecione o período e a pergunta sobre custo ou uso que precisa responder. | Agrupe ou filtre dados para identificar a parte do gasto relacionada à pergunta. | Investigue a mudança nos recursos. Um aumento pode ter várias causas; a ferramenta mostra dados, não decide a ação sozinha.
budgets | Defina a meta e quais condições devem gerar um aviso ou ação compatível. | Configure destinatários e acompanhe valores observados ou previstos conforme a ferramenta. | Ao receber um aviso, investigue e realize a ação pertinente. Um orçamento não é, por padrão, interrupção rígida de todo consumo.
pricing-calculator-cur-e-outras-ferramentas | Antes do uso, estime a capacidade e as condições previstas na calculadora. | Depois do uso, analise registros e relatórios para entender o consumo ocorrido. | Compare hipóteses e realidade. Estimativa e relatório respondem perguntas diferentes e não são garantias de uma fatura fixa.
planos-de-suporte | Identifique a necessidade de ajuda e o impacto real do problema. | Confira a oferta aplicável e abra um caso elegível com informações suficientes para o atendimento. | Acompanhe investigação e ações. Primeira resposta, resolução e operação cotidiana da aplicação são responsabilidades distintas.
recursos-de-ajuda-e-parceiros | Descreva se precisa aprender, esclarecer uma dúvida, comprar software ou contratar execução de um trabalho. | Escolha o canal ou a oferta que tem esse papel e examine suas condições. | Valide a orientação ou a entrega. Fórum, suporte, loja e parceiro não oferecem a mesma responsabilidade.
midia-e-jogos | Separe preparação de mídia, transmissão ao vivo e hospedagem de partidas. | Identifique o produto associado à etapa específica e confira sua oferta e suas restrições. | Compare o resultado com a necessidade. Esta ficha é de referência e não uma recomendação de uso de ofertas antigas.
iot-robotica-e-satelite | Separe conexão de dispositivos, monitoramento físico, robótica e comunicação com satélites. | Leia o papel do produto específico e seus requisitos físicos e comerciais. | Confira a disponibilidade e o resultado esperado. A categoria não representa um único serviço intercambiável.
desenvolvimento-e-aplicacoes | Descubra se a tarefa envolve configuração, análise de código, modelagem de recursos ou modernização. | Leia o produto correspondente e suas condições atuais; não escolha apenas pelo nome da categoria. | Compare a ferramenta ao trabalho concreto. Algumas ofertas do material são históricas e têm restrições indicadas.
rede-e-diretorio | Defina se precisa localizar um serviço, conectar aplicações, avaliar caminhos ou organizar entidades. | Selecione a ferramenta com aquela função e prepare o escopo de recursos e identidades. | Verifique a comunicação ou organização obtida. Descoberta de serviços não é o mesmo que cadastro de usuários.
gerenciamento-e-custos | Diferencie conservação de cópias, comunicação operacional e assistência de implantação. | Use a ferramenta pertinente ao recurso e à tarefa, considerando sua oferta atual. | Confira o resultado no ambiente. Um complemento de operação não substitui todas as ferramentas centrais de custo e governança.
"""
for linha in _DADOS.strip().splitlines():
    chave, *passos = [p.strip() for p in linha.split('|')]
    assert len(passos) == 3 and all(passos) and chave not in PASSOS, chave
    PASSOS[chave] = passos
